### ISSUE TITLE
Error running `pip install virtualenv` under pypy-5.4

### ISSUE THREAD

**Issue by alex** [pypa/virtualenv#1639] opened 2020-02-15 21:48 UTC
Full log here: https://travis-ci.org/pyca/cryptography/jobs/650916996

Relevant bit:

```
+pip install virtualenv
Collecting virtualenv
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/a3/dd/e43866ac0d25cd1ecbde0814f6cd7372ea257fbdf443dc9f0a01740da93d/virtualenv-20.0.4-py2.py3-none-any.whl (4.6MB)
    100% |████████████████████████████████| 4.6MB 259kB/s 
Collecting appdirs<2,>=1.4.3 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting distlib<1,>=0.3.0 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/7d/29/694a3a4d7c0e1aef76092e9167fbe372e0f7da055f5dcf4e1313ec21d96a/distlib-0.3.0.zip (571kB)
    100% |████████████████████████████████| 573kB 2.4MB/s 
Collecting filelock<4,>=3.0.0 (from virtualenv)
  Cache entry deserialization failed, entry ignored
Requirement already satisfied (use --upgrade to upgrade): six<2,>=1.9.0 in /home/travis/virtualenv/pypy-5.4/site-packages (from virtualenv)
Collecting contextlib2<1,>=0.6.0; python_version < "3.3" (from virtualenv)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Collecting pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" (from virtualenv)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
Collecting importlib-resources<2,>=1.0; python_version < "3.7" (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl
Collecting importlib-metadata<2,>=0.12; python_version < "3.8" (from virtualenv)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/8b/03/a00d504808808912751e64ccf414be53c29cad620e3de2421135fcae3025/importlib_metadata-1.5.0-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv)
  Cache entry deserialization failed, entry ignored
Collecting typing; python_version < "3.5" (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv)
  Downloading https://files.pythonhosted.org/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/60/85/668bca4a9ef474ca634c993e768f12bd99af1f06bb90bb2655bc538a967e/zipp-2.2.0.tar.gz
  Running setup.py (path:/tmp/pip-build-9J1yCN/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments.
Collecting configparser>=3.5; python_version < "3" (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Building wheels for collected packages: distlib, unknown, unknown
  Running setup.py bdist_wheel for distlib ... done
  Stored in directory: /home/travis/.cache/pip/wheels/6e/e8/db/c73dae4867666e89ba3cfbc4b5c092446f0e584eda6f409cbb
  Running setup.py bdist_wheel for unknown ... done
  Stored in directory: /home/travis/.cache/pip/wheels/a0/1f/9d/d132b3fbc38b33322681e3a7830c0a29fce7f55c3a06b85c65
  Running setup.py bdist_wheel for unknown ... error
  Complete output from command /home/travis/virtualenv/pypy-5.4/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9J1yCN/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp_INCqIpip-wheel- --python-tag pp254:
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-9J1yCN/unknown/setup.py'
  
  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown
  Complete output from command /home/travis/virtualenv/pypy-5.4/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9J1yCN/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-9J1yCN/unknown/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for unknown
```

It's deeply unclear to me what is happening -- I don't have a clue what all these "unknown" values are. Normally I'd assume that was a pip bug, but since virtualenv just underwent a substantial rewrite...

**Comment by xavfernandez** [comment] 2020-02-15 22:00
It likely comes from your old  `pip 8.1.2` version that does not understand `pyproject.toml` (and also the fact that it uses an old setuptools that does not understand `setup.cfg`.

**Comment by alex** [comment] 2020-02-15 22:04
I'm attempting to update pip before installing virtualenv with it, will report back on how that works.

**Comment by alex** [comment] 2020-02-15 22:13
Upgrading pip seems to solve this. If that's considered sufficient, I'm happy to close this.

**Comment by gaborbernat** [comment] 2020-02-15 22:18
Consider this duplicate of https://github.com/pypa/virtualenv/issues/1618

**Closed by gaborbernat** 2020-02-15 22:18 UTC

**Comment by gaborbernat** [comment] 2020-02-15 22:19
@xavfernandez the zipp dependency is not installed from wheel, that's where the error comes from.
