### ISSUE TITLE
bin/activate not running with zsh shell

### ISSUE THREAD

**Issue by ameliesc** [pypa/virtualenv#1692] opened 2020-03-05 13:25 UTC
**Issue**

when trying to activate a virtualenvironment using 
`source bin/activate` 
I kept getting the following error:
`(eval):1: defining function based on alias 'deactivate' `
`(eval):1: parse error near '()'`

I figured this is due the the script not parsing correctly in zsh, no Idea why this suddenly is happening I did not have this problem before updating my system recently. Although the new default on MacOS is zsh now I did use it before without any issues. 

I fixed the issue by adding:

`if [ -n "$ZSH_VERSION" ]; then emulate -L ksh; fi`

above the deactivate function. 

**Environment**

- OS: macOS Catalina
- `/usr/local/bin/pip`
- `/usr/local/bin/virtualenv`

**Comment by gaborbernat** [comment] 2020-03-06 13:56
what's your zsh version? 🤔 

```
C02X4E3DJG5J% source bin/activate
(py3) C02X4E3DJG5J% zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)
```

Seems to work for me.

**Comment by ameliesc** [comment] 2020-03-06 14:10
my zsh version is 

`zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)`

**Comment by gaborbernat** [comment] 2020-03-06 14:31
From my above test, there must be something else at play in your case, as it seems to work with both 5.3 and 5.8 for myself. Can you look around what could cause that error?

**Comment by gaborbernat** [comment] 2020-03-09 17:31
Closing due to the lack of reproduce-ability; if someone else manages to do so we can reopen.

**Closed by gaborbernat** 2020-03-09 17:31 UTC
Labels: help-wanted, needs-reproducer

**Comment by jared-maguire** [comment] 2020-07-25 21:55
@gaborbernat @ameliesc 

I also have this issue. Started immediately after Catalina upgrade. My zsh version and virtualenv error message are exactly as @ameliesc's. 

I've been using zsh as my shell on MacOS for 10+ years, and virtualenv for ~8 years and this is the first time this problem has appeared. 

Did you try to reproduce with `zsh 5.7.1 (x86_64-apple-darwin19.0)` on Catalina? Perhaps apple did something odd with their new zsh build.

**Comment by gaborbernat** [comment] 2020-07-25 21:56
Virtualenv version number? Detailed description what's happening?

**Comment by jared-maguire** [comment] 2020-07-25 22:13
Oh dear! When looking for the version number I realized I'm using `venv` in this case, not `virtualenv`! (It's some google tutorial I'm building off of, so I hadn't noticed their example is not using full on virtualenv). So, not a virtualenv problem at all. Apologies! 

I wonder if @ameliesc didn't make the same mistake as me -- her workaround also worked for me. :shrug:

ps: thanks for the very quick response!
