### ISSUE TITLE
optionally create pythonw link in virtualenv for framework python builds on osx

### ISSUE THREAD

**Issue by vbabiy** [pypa/virtualenv#54] opened 2011-03-14 21:35 UTC
http://groups.google.com/group/python-virtualenv/browse_thread/thread/83fa4a12d22a30c8/744e19c194f1618a?#744e19c194f1618a details how wxpython might be enabled for python on OSX in virtualenvs by analogy with the way it currently works for win32 and cygwin installation modes. 

Ian's previous discussion along these lines is here:
http://groups.google.com/group/python-virtualenv/browse_thread/thread/b119a3c26aa49238
and the code that does it at the moment is listed here:
http://github.com/gldnspud/virtualenv-pythonw-osx/

Can we get this baked into the core distribution? What would need to change about the approach?

---
- Bitbucket: https://bitbucket.org/ianb/virtualenv/issue/65
- Originally Reported By: dan mackinlay
- Originally Created At: 2010-09-22 09:09:54

**Comment by nils-werner** [comment] 2015-03-06 11:19
A fix for this in sight? I still have the issue with shy Matplotlib windows

**Comment by nils-werner** [comment] 2015-11-24 10:55
This issue is 4,5 years old and [requires ugly hacks to make matplotlib run on Mac OSX](http://matplotlib.org/1.5.0/faq/virtualenv_faq.html#osx). **Can we please fix this?**

**Comment by stlk** [comment] 2015-11-29 08:57
I second this. I installed python 2.7 and then created virtualenv using following commands:
```
brew install python --framework
virtualenv env
source env/bin/activate
pip install matplotlib
```

But I get following message when I try to import `matplotlib.pyplot `.

```
Python 2.7.10 (default, Aug 22 2015, 20:33:39)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
>>> import matplotlib.pyplot as plt
...
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

Workaround mentioned by @nils-werner works. But its huge blocker for beginners who want to work with matplotlib(not only) in jupyter notebook in virtualenv.

**Comment by terrycojones** [comment] 2015-11-29 22:44
Ugh....... I just hit this as well, following an upgrade to matplotlib 1.5 (which now fails to import a backend, as documented above by @stlk). I'm using a brew installed python 3.5.

**Comment by thomasdziedzic** [comment] 2015-11-30 05:27
Was going through an intro to visualization using python chapter, and I can't even begin writing the first code sample in jupyter because I keep hitting this issue on a mac... I'm using the system python that comes with mac.

**Comment by mturilli** [comment] 2015-12-14 13:30
+1

**Comment by arsenico13** [comment] 2016-01-03 17:07
+1
Oh god....
issue from 2011.. still **not fixed**.

**Comment by tjanson** [comment] 2016-01-31 00:24
For the mean time, the utility that’s linked in this issue (and on the FAQ) still worked for me:

```sh
$ # install the utility
$ pip install git+https://github.com/gldnspud/virtualenv-pythonw-osx.git
$ # enter the virtualenv with virtualenvwrapper (or manually)
$ workon my-venv
$ # double-check that this is your venv Python binary
$ which python
/Users/macbook/.virtualenvs/my-venv/bin/python
$ # fix it, using magic
$ fix-osx-virtualenv `which python`/../..
```
Yes, it’s quite simple, but took me a while to figure out. I have no idea what this does, but as a result Matplotlib works by simply invoking it using that venv Python binary – no need for a wrapper shell function.

**Comment by nils-werner** [comment] 2016-01-31 14:01
I know this solution but:

 - You need to repeat (and remember how to do so) it for all your virtualenvs
 - It fails with certain external modules or when using CFFI or something (will need to go check what it was exactly)

**Comment by RobertCoop** [comment] 2016-02-10 19:48
It doesn't feel like an ideal solution, but an easy workaround is to use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.org/) and then use the hooks to configure things.  Install virtualenv-pythonw-osx and virtualevnwrapper, source the virtualenvwrapper.sh file in order to create the hook scripts, then add the following to the `postactivate` script:

```
if [ ! -d $VIRTUAL_ENV/Python.app ]; then
  echo Fixing OSX Python display issues...
  fix-osx-virtualenv $VIRTUAL_ENV
fi
```

This will automatically fix any virtual environment when you activate them via the `workon` command

**Comment by RexFuzzle** [comment] 2016-03-31 07:34
+1

**Comment by iannesbitt** [comment] 2016-05-07 22:30
+1

**Comment by bmaher74** [comment] 2016-05-12 01:18
+1

**Comment by visualmotive** [comment] 2016-05-30 19:29
Just hit this bug, too. The workaround suggested are not exactly elegant. Would be great to get fixed!

**Comment by wwp3** [comment] 2016-06-02 06:12
**Try changing the matplotlib backend to get matplotlib to work in a virtual environment:**

There are (at least) two solutions I've used, with some additional methods included below. Both outlined here should to the same thing with a slightly different approach:

If you already installed matplotlib using pip on your virtual environment, you can...

_1. Add a new matplotlibrc file for your virtual environment_
For example, in your virtual environment run:
```
$ cd ~/.matplotlib
$ nano matplotlibrc #to create file using nano
```
Write `backend: TkAgg` in the file and save upon exit. You should be good to go.

****OR****

_2. Edit the matplotlibrc file referenced by your virtual environment_
In your virtual environment, open a python shell and run:
```
>>> import matplotlib
>>> matplotlib.matplotlib_fname()
'/home/foo/.config/matplotlib/matplotlibrc'
```
This displays the matplotlibrc file referenced by the matplotlib package in your virtual environment. Follow the path and open the matplotlibrc file. Edit the file's `backend` tag to read `backend: TkAgg` and `save`


[**Also** - _A third approach_]
Haven't tried before, but according to documentation you should be able to define the backend upon import of matplotlib if you don't want to change the backend in the script itself:
```
import matplotlib
matplotlib.use('TkAgg')
```


(see sources below for further explanation and additional methods)

Sources:
[1] http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
[2] http://matplotlib.org/users/customizing.html#customizing-matplotlib
[3] http://stackoverflow.com/questions/4130355/python-matplotlib-framework-under-macosx
[4] http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv

**Comment by visualmotive** [comment] 2016-06-02 13:44
@wwp3 Great write-up, thanks! I have had good luck with this option: 

```
import matplotlib
matplotlib.use('TkAgg')
```

**Comment by jenshnielsen** [comment] 2016-07-15 16:39
Working on improving the Matplotlib docs for this issue @stlk any objections to using part of your guide for the fix to the Jupyter notebook issue (We already have the terminal python/ipython covered )

**Comment by stlk** [comment] 2016-07-15 16:43
@jenshnielsen Feel free to use it, I'm happy it's helpful.

**Comment by jucor** [comment] 2016-08-22 10:34
+1

**Comment by mattayes** [comment] 2016-10-20 19:41
:+1:

**Comment by jenshnielsen** [comment] 2016-10-21 09:29
It's not

**Comment by nils-werner** [comment] 2016-10-25 10:53
Absolutely not. It is worse than ever before as it crashes on `import`. Steps to reproduce

    virtualenv test
    source test/bin/activate
    pip install matplotlib
    python -c "import matplotlib.pyplot; print 'import succeeded'"

**Comment by pfmoore** [comment] 2016-10-25 11:15
Is there a PR that fixes this? If so, have the people encountering the issue tested it and confirms that it resolves the problem? If there isn't, is anyone working on one? It's going to be more or less impossible for anyone who can't reproduce the issue (which needs, I guess, an OSX installation at a minimum to do) to develop a fix, so we're relying on contributions here.

@nils-werner thanks for the clear description of how to reproduce. If you could add environment details (all I see in the thread is "OSX", but nothing specific about whether it's all versions, what version of virtualenv and python and how they were installed, whether certain other things need to be installed, how to install them, etc) that would be helpful as well.

Then hopefully someone with access to a suitable environment can produce a PR and reference it here. At that stage, we can review the PR and take it from there.

**Comment by tjanson** [comment] 2016-10-25 11:27
@pfmoore I have been using [the workaround in my earlier comment](https://github.com/pypa/virtualenv/issues/54#issuecomment-177344059), which still consistently works for me. (For the record: OS X 10.11.6, Python 3.5.2, matplotlib-1.5.3.)

**Comment by jenshnielsen** [comment] 2016-10-25 11:31
@nils-werner The only reason it's worse it that we explicitly check for a framework build before running the OSX backend in Matplotlib https://github.com/matplotlib/matplotlib/blob/master/src/_macosx.m#L3071

The alternative is a soft failure where the gui is only partially functional.

WXPython has a similar check build in which prevents you from using WXPython from a non framework build. 

The best workaround is to use venv from the standard library if you are using python3 
Unlike virtualenv that works correctly.
http://matplotlib.org/devdocs/faq/osx_framework.html#introduction

**Comment by pfmoore** [comment] 2016-10-25 11:37
OK, so I guess if no-one is working on a PR, the resolution here is either:

1. If you're on Python 3, use stdlib ```venv```
2. Otherwise, use the workaround noted.

Cool. I'm not sure if it's worth leaving the issue open in that case - there's a clear workaround, and any code fix would be a new PR anyway. I suggest we close the issue - comments?

**Comment by ashishprajapati** [comment] 2018-05-28 21:02
@wwp3 Great, thanks! I successfully fixed it with this option:

1. Add a new matplotlibrc file for your virtual environment
For example, in your virtual environment run:

$ cd ~/.matplotlib
$ nano matplotlibrc #to create file using nano
Write backend: TkAgg in the file and save upon exit. You should be good to go.

**Comment by dendisuhubdy** [comment] 2018-10-24 21:44
@stlk that was helpful thank you

**Closed** 2019-01-30 16:11 UTC
Labels: enhancement, import, wontfix

**Comment by rex201899** [comment] 2019-05-10 16:24
> **Try changing the matplotlib backend to get matplotlib to work in a virtual environment:**
> 
> There are (at least) two solutions I've used, with some additional methods included below. Both outlined here should to the same thing with a slightly different approach:
> 
> If you already installed matplotlib using pip on your virtual environment, you can...
> 
> _1. Add a new matplotlibrc file for your virtual environment_
> For example, in your virtual environment run:
> 
> ```
> $ cd ~/.matplotlib
> $ nano matplotlibrc #to create file using nano
> ```
> 
> Write `backend: TkAgg` in the file and save upon exit. You should be good to go.
> 
> _**_OR**__
> 
> _2. Edit the matplotlibrc file referenced by your virtual environment_
> In your virtual environment, open a python shell and run:
> 
> ```
> import matplotlib
> matplotlib.matplotlib_fname()
> '/home/foo/.config/matplotlib/matplotlibrc'
> ```
> 
> Note/Update: if you get a syntax error in your virtual environment, you might need to simply run:
> 
> ```
> import matplotlib
> matplotlib.matplotlib_fname()
> ```
> 
> This displays the matplotlibrc file referenced by the matplotlib package in your virtual environment. Follow the path and open the matplotlibrc file. Edit the file's `backend` tag to read `backend: TkAgg` and `save`
> 
> [**Also** - _A third approach_]
> Haven't tried before, but according to documentation you should be able to define the backend upon import of matplotlib if you don't want to change the backend in the script itself:
> 
> ```
> import matplotlib
> matplotlib.use('TkAgg')
> ```
> 
> (see sources below for further explanation and additional methods)
> 
> Sources:
> [1] http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
> [2] http://matplotlib.org/users/customizing.html#customizing-matplotlib
> [3] http://stackoverflow.com/questions/4130355/python-matplotlib-framework-under-macosx
> [4] http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv

Your first solution is so great and have solved my problem. Thx!
