### ISSUE TITLE
ImportError: cannot import name 'ensure_text'

### ISSUE THREAD

**Issue by johnthagen** [pypa/virtualenv#1551] opened 2020-02-10 13:03 UTC
Apologies I don't have a completely reproducible environment yet, but since `virtualenv==20.0.0` was released [3 hours ago](https://pypi.org/project/virtualenv/) I wanted to get this reported as soon as I could as it likely could affect others.

I'm not 100% certain this is `virtualenv`'s fault, but I have previous builds that worked and the only major difference between them (and last week) was `virtualenv` being updated to a new major version.

If submitting a BUG please provide:

Operating System:

- ubuntu1804 Docker Image on `gitlab-runner 12.3.0`
- Python 3.6
- Running with a `tox` environment

```
$ apt-get update && apt-get install -y python3-pip python3-dev apt-rdepends libpq-dev libffi-dev && /usr/bin/python3 -m pip install tox && /usr/bin/python3 -m tox -e job
...
...
932 Collecting tox
933   Downloading https://files.pythonhosted.org/packages/77/a7/a5b721d9bf955edfe36013e5ecc9136fc6b2fef622ab1797ff0560273d8e/tox-3.14.3-py2.py3-none-any.whl (80kB)
934 Collecting virtualenv>=16.0.0 (from tox)
935   Downloading https://files.pythonhosted.org/packages/62/89/72ab7d18e001a23b25eb75ce71bbf9e2a3c142e2dad2e4e2b88012e4ca25/virtualenv-20.0.0-py2.py3-none-any.whl (4.6MB)
936 Collecting importlib-metadata<2,>=0.12; python_version < "3.8" (from tox)
937   Downloading https://files.pythonhosted.org/packages/8b/03/a00d504808808912751e64ccf414be53c29cad620e3de2421135fcae3025/importlib_metadata-1.5.0-py2.py3-none-any.whl
938 Requirement already satisfied: six<2,>=1.0.0 in /usr/lib/python3/dist-packages (from tox)
939 Collecting filelock<4,>=3.0.0 (from tox)
940   Downloading https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
941 Collecting toml>=0.9.4 (from tox)
942   Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
943 Collecting packaging>=14 (from tox)
944   Downloading https://files.pythonhosted.org/packages/98/42/87c585dd3b113c775e65fd6b8d9d0a43abe1819c471d7af702d4e01e9b20/packaging-20.1-py2.py3-none-any.whl
945 Collecting py<2,>=1.4.17 (from tox)
946   Downloading https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl (83kB)
947 Collecting pluggy<1,>=0.12.0 (from tox)
948   Downloading https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
949 Collecting importlib-resources<2,>=1.0; python_version < "3.7" (from virtualenv>=16.0.0->tox)
950   Downloading https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl
951 Collecting appdirs<2,>=1.4.3 (from virtualenv>=16.0.0->tox)
952   Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
953 Collecting zipp>=0.5 (from importlib-metadata<2,>=0.12; python_version < "3.8"->tox)
954   Downloading https://files.pythonhosted.org/packages/46/42/f2dd964b2a6b1921b08d661138148c1bcd3f038462a44019416f2342b618/zipp-2.2.0-py36-none-any.whl
955 Collecting pyparsing>=2.0.2 (from packaging>=14->tox)
956   Downloading https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl (67kB)
957 Installing collected packages: zipp, importlib-metadata, importlib-resources, appdirs, filelock, virtualenv, toml, pyparsing, packaging, py, pluggy, tox
958 Successfully installed appdirs-1.4.3 filelock-3.0.12 importlib-metadata-1.5.0 importlib-resources-1.0.2 packaging-20.1 pluggy-0.13.1 py-1.8.1 pyparsing-2.4.6 toml-0.10.0 tox-3.14.3 virtualenv-20.0.0 zipp-2.2.0
959 job create: /builds/.tox/job
960 ERROR: invocation failed (exit code 1), logfile: /builds/.tox/job/log/job-0.log
961 ================================== log start ===================================
962 ERROR:root:ImportError: cannot import name 'ensure_text'
```

**Comment by Larandar** [comment] 2020-02-10 13:05
I have similar problems with `from pkg_resources import get_distribution ModuleNotFoundError: No module named 'pkg_resources'` starting 3 hours ago in every CI job.

**Comment by johnthagen** [comment] 2020-02-10 13:12
cc @gaborbernat for awareness

**Comment by gaborbernat** [comment] 2020-02-10 13:28
@Larandar can you post a link? The error could mean our application data folder is missing for some reason. Ideally for reproducing and fixing the issue, we'd want the ``virtualenv --vvv`` output, so we can know better what's happening. Apologies for the disruption this might cause to you.

**Comment by tobiasbrunner** [comment] 2020-02-10 13:52
Ran into the same issue on Travis CI ([log](https://travis-ci.org/strongswan/strongswan/jobs/648386815#L3255)). `virtualenv` is pulled in as dependency of `tox` via `pip install --user tox`, which results in this error ([line 997 in the log](https://travis-ci.org/strongswan/strongswan/jobs/648386815#L997)):

```
ERROR: virtualenv 20.0.0 has requirement six<2,>=1.12.0, but you'll have six 1.11.0 which is incompatible.
```

**Comment by joker-official** [comment] 2020-02-10 13:54
Same problem here, after downgrading to `16.7.9` it worked again, then after upgrading to `20.0.0` it also updated `six` to `1.14.0`, which made it work. So somehow the `six` dependency was missing ... what I can see from the logs, `virtualenv` was pulled in from `pip install tox`.
```
+ pip install tox
Collecting tox
  Downloading https://files.pythonhosted.org/packages/77/a7/a5b721d9bf955edfe36013e5ecc9136fc6b2fef622ab1797ff0560273d8e/tox-3.14.3-py2.py3-none-any.whl (80kB)
    100% |################################| 81kB 4.4MB/s 
25hCollecting filelock<4,>=3.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Collecting packaging>=14 (from tox)
  Downloading https://files.pythonhosted.org/packages/98/42/87c585dd3b113c775e65fd6b8d9d0a43abe1819c471d7af702d4e01e9b20/packaging-20.1-py2.py3-none-any.whl
Requirement already satisfied: six<2,>=1.0.0 in /usr/lib/python2.7/dist-packages (from tox)
Collecting virtualenv>=16.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/62/89/72ab7d18e001a23b25eb75ce71bbf9e2a3c142e2dad2e4e2b88012e4ca25/virtualenv-20.0.0-py2.py3-none-any.whl (4.6MB)
    100% |################################| 4.6MB 212kB/s 
```
No error on that `pip` command, only `ImportError: cannot import name 'ensure_text'` when trying to use it.

**Comment by johnthagen** [comment] 2020-02-10 13:56
I can confirm that in my initial docker/tox failure case that changing

```
/usr/bin/python3 -m pip install tox
``` 

to

```
/usr/bin/python3 -m pip install tox "virtualenv<20.0.0"
```

Worked around the problem for now.

**Comment by webknjaz** [comment] 2020-02-10 14:13
Looks like this is happening under PyPy: https://travis-ci.org/PyCQA/astroid/jobs/648355483#L263.

**Comment by joker-official** [comment] 2020-02-10 14:27
We worked around the problem with `pip install tox "six>=1.14.0"`. Seems to be a pip issue with resolving depdencies to me, maybe https://github.com/pypa/pip/issues/988

**Comment by webknjaz** [comment] 2020-02-10 14:30
@joker-official [virtualenv specifies `six>=1.12.0,<2`][1] so it's natural that Pip doesn't upgrade six if it already matches that constraint.

[1]: https://github.com/pypa/virtualenv/blob/5c9b624/setup.cfg#L45

**Comment by joker-official** [comment] 2020-02-10 14:33
@webknjaz My system had `1.11.0` though, which seems to only match `tox`'s requirements.

**Comment by webknjaz** [comment] 2020-02-10 14:34
@joker-official inside or outside of venvs created by tox?

**Comment by pfmoore** [comment] 2020-02-10 14:35
@joker-official Yes, that sounds like pypa/pip#988.

**Comment by joker-official** [comment] 2020-02-10 14:35
@webknjaz  Outside. Installed via `python-six` ubuntu package. I'm unable to create virtualenvs without the new six ;)

**Comment by webknjaz** [comment] 2020-02-10 14:37
@joker-official messing with the system-wide Python installation is not a good idea...

**Comment by joker-official** [comment] 2020-02-10 14:39
@webknjaz I'm aware, but that's not the issue at hand (and these are short-living docker-containers anyways).

**Comment by gaborbernat** [comment] 2020-02-10 14:56
This feels like an issue for pip under:

> @joker-official Yes, that sounds like [pypa/pip#988](https://github.com/pypa/pip/issues/988). Specifically
> 
> > "first found wins" behavior for dependency requirements/constraints, which results in not respecting all constraints.


I'll close this for now.

@Larandar your issue is different please open a separate issue for that.

**Closed by gaborbernat** 2020-02-10 14:56 UTC

**Comment by asottile** [comment] 2020-02-10 18:34
this seems pretty bad :/

here's a minimal reproduction:

```dockerfile
FROM ubuntu:bionic
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3-distutils \
        python3-pip \
        python3-setuptools \
        python3-six \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install pre-commit
RUN virtualenv /venv
```

and now my users are complaining to me about it: https://github.com/pre-commit/pre-commit/issues/1325

**Comment by gaborbernat** [comment] 2020-02-10 18:35
There's not much we can do here; see https://github.com/pre-commit/pre-commit/issues/1325#issuecomment-584280357. We specify a version constraint correctly as per the python ecosystem.

**Comment by asottile** [comment] 2020-02-10 18:36
One fix would be to not depend on `ensure_text` here -- almost all of the cases should use `six.text_type(...)` anyway

**Comment by gaborbernat** [comment] 2020-02-10 18:37
I do not agree on this with you @asottile and that is not a solution, it's a workaround that pins our dependencies back in the past.

**Comment by asottile** [comment] 2020-02-10 18:38
fwiw this was suggested during the feedback period here: https://github.com/pypa/virtualenv/pull/1481#discussion_r363314464

**Comment by gaborbernat** [comment] 2020-02-10 18:45
And I thought using the ``ensure_text\ensure_str`` is cleaner so did not address it there. The problem is not using those functions, but rather than people tend to install pip packages on top of Ubuntu packages which can blow up with such edge cases.

**Comment by gaborbernat** [comment] 2020-02-10 19:01
That being said if someone tries to port it over to the suggested text_type approach I'll review it.

**Comment by asottile** [comment] 2020-02-10 19:20
for related reading, setuptools hit a similar thing when unvendoring -- especially with `six`:
- https://github.com/pypa/setuptools/issues/947
- https://github.com/pypa/setuptools/commit/edfa86809c0010caaa24b65c0e84c8467ba43b2b
- https://github.com/pypa/setuptools/issues/980

**Comment by odyssey4me** [comment] 2020-02-11 22:37
@Larandar I think you may be hitting https://github.com/pypa/setuptools/issues/1990 instead.

**Comment by ssbarnea** [comment] 2020-02-12 13:35
Can we please reopen this bug?  The reality is that is perfectly possible to end-up with a newer virtualenv with a six version that is too old.

Here is an example: https://logserver.rdoproject.org/16/24916/5/check/check-centos-8/595187c/job-output.txt

**Comment by gaborbernat** [comment] 2020-02-12 13:37
The issue is on pip side, not much we can do about it 🤷‍♂️

**Comment by deadpyxel** [comment] 2020-11-04 23:37
I have been facing this issue since a recent update. Currently running version 20.1.0 I'm not sure if there was a regression or I'm just suffering from release cycles. I'm running an Archlinux and updated virtualenv last night I've been unable to create new virtualenvs with `virtualenv venv`.

**Comment by asottile** [comment] 2020-11-04 23:41
@deadpyxel can you show your full output and command? it's probably not the same as this issue since this was fixed a long time ago

**Comment by deadpyxel** [comment] 2020-11-05 02:37
Sure, if I run `virtualenv venv` for example:
```
ImportError: cannot import name 'enquote_executable' from 'distlib.scripts' (/home/sidious/.local/lib/python3.8/site-packages/distlib/scripts.py)
```
This is the only output I get. If I add a `--verbose`:
```
find interpreter for spec PythonSpec(path=/usr/bin/python)
proposed PythonInfo(spec=CPython3.8.6.final.0-64, exe=/usr/bin/python, platform=linux, version='3.8.6 (default, Sep 30 2020, 04:00:38) \n[GCC 10.2.0]', encoding_fs_io=utf-8-utf-8)
ImportError: cannot import name 'enquote_executable' from 'distlib.scripts' (/home/sidious/.local/lib/python3.8/site-packages/distlib/scripts.py)
```

**Comment by deadpyxel** [comment] 2020-11-05 02:57
As additional info, After some digging and testing different versions I found out that the version pushed on October 16, 20.0.25 on Archlinux packages still works as intended, and any version after that one faces the same issue. This may be an Archlinux only problem, so I'm not really sure how to proceed.

I used ALA (Archlinux Archives) to test the multiple versions, found here: https://archive.archlinux.org/packages/p/python-virtualenv/

**Comment by asottile** [comment] 2020-11-05 04:22
yeah that's a completely different error message -- not sure why you thought it was the same

please open a new issue
