### ISSUE TITLE
Creating new enviroment 

### ISSUE THREAD

**Issue by osama12sy** [pypa/virtualenv#1350] opened 2019-05-01 15:42 UTC
Hello when I try to create new virtual environment for installing tensorflow I have this issue
```
Running virtualenv with interpreter C:\Users\user\AppData\Local\Programs\Python\Python37-32\python.exe
Using base prefix 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python37-32'
New python executable in C:\Users\user\venv\Scripts\python.exe
Command C:\Users\user\venv\Scripts\python.exe -m pip config list had error code 1
Installing setuptools, pip, wheel...

Complete output from command C:\Users\user\venv\Scripts\python.exe - setuptools pip wheel:
Traceback (most recent call last):
File "<stdin>", line 3, in <module>
ModuleNotFoundError: No module named 'pkgutil'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\virtualenv.py", line 2567, in <module>
    main()
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\virtualenv.py", line 1088, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\virtualenv.py", line 1025, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\virtualenv.py", line 886, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command C:\Users\user\venv\Scripts\python.exe - setuptools pip wheel failed with error code 1
```

**Comment by gaborbernat** [comment] 2019-05-01 15:45
Duplicate of https://github.com/pypa/virtualenv/issues/1350

**Closed by gaborbernat** 2019-05-01 15:45 UTC

**Comment by pfmoore** [comment] 2019-05-01 16:17
Did you just mark this as a duplicate of itself?

**Comment by gaborbernat** [comment] 2019-05-01 16:21
My bad wanted to point to https://github.com/pypa/virtualenv/issues/1204 🤦‍♂
