### ISSUE TITLE
Wrong prompt while using oh-my-posh

### ISSUE THREAD

**Issue by dsptanmay** [pypa/virtualenv#1920] opened 2020-08-12 17:52 UTC
**Issue**

The prompt when activating virtual environments created using virtualenv appears to be wrong. This can be noticed with [oh-my-posh.](https://github.com/JanDeDobbeleer/oh-my-posh)
Image for reference:

![image](https://user-images.githubusercontent.com/39451995/90048305-f17d3d80-dcf0-11ea-8866-59f8b8fcbaf9.png)
(Theme: robbyrussell)
----
![image](https://user-images.githubusercontent.com/39451995/90049509-85033e00-dcf2-11ea-8f50-27d360dc83a9.png)
(Theme: Honukai)
----
NOTE: This issue appears sometimes only. For example, if I restart the shell a couple of times, it goes back to normal.

**Expected Behaviour**
The prompt should include only one instance of ```.venv```. I have noticed this issue only with virtualenv. The prompts generated using virtual environments created by the in-built ``venv`` module appear to be fine.

**Environment**

- OS: Windows 10 64-bit version 2004
- ``pip list`` of the host python where ``virtualenv`` is installed:
```
appdirs                1.4.4
asgiref                3.2.10
astroid                2.4.2
atomicwrites           1.4.0
attrs                  19.3.0
autopep8               1.5.3
backcall               0.2.0
bcrypt                 3.1.7
beautifulsoup4         4.9.1
black                  19.10b0
bleach                 3.1.5
blessings              1.7
branca                 0.4.1
Brotli                 1.0.7
certifi                2020.6.20
cffi                   1.14.0
chardet                3.0.4
click                  7.1.2
cloudpickle            1.4.1
colorama               0.4.3
colorlover             0.3.0
console-menu           0.6.0
cryptography           2.9.2
cycler                 0.10.0
decorator              4.4.2
decorators             0.1.1
defusedxml             0.6.0
Deprecated             1.2.10
diff-match-patch       20181111
distlib                0.3.1
docutils               0.16
entrypoints            0.3
filelock               3.0.12
flake8                 3.8.3
folium                 0.11.0
greenlet               0.4.16
gTTS                   2.1.1
gTTS-token             1.1.3
helpdev                0.7.1
idna                   2.10
importlib-metadata     1.6.1
intervaltree           3.0.2
ipykernel              5.3.0
ipython                7.17.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
isort                  4.3.21
jedi                   0.17.1
Jinja2                 2.11.2
jsonschema             3.2.0
jupyter-client         6.1.6
jupyter-core           4.6.3
keyring                21.3.0
kivy-deps.angle        0.2.0
kiwisolver             1.2.0
lazy-object-proxy      1.4.3
llvmlite               0.33.0
lxml                   4.5.1
MarkupSafe             1.1.1
matplotlib             3.2.2
mccabe                 0.6.1
mistune                0.8.4
more-itertools         8.4.0
msgpack                1.0.0
mutagen                1.44.0
mypy                   0.781
mypy-extensions        0.4.3
nbconvert              5.6.1
nbformat               5.0.7
neovim                 0.3.1
notebook               6.0.3
numba                  0.50.0
numpy                  1.19.0
oauthlib               3.1.0
packaging              20.4
pafy                   0.5.5
pandas                 1.1.0
pandas-datareader      0.8.1
pandocfilters          1.4.2
paramiko               2.7.1
parso                  0.7.0
pathspec               0.8.0
pathtools              0.1.2
pbr                    5.4.5
pexpect                4.8.0
pickleshare            0.7.5
pip                    20.2.2
pip-autoremove         0.9.1
pkginfo                1.5.0.1
pluggy                 0.13.1
plumbum                1.6.9
prettytable            0.7.2
prometheus-client      0.8.0
prompt-toolkit         3.0.5
psutil                 5.7.0
ptyprocess             0.6.0
py                     1.8.2
pycodestyle            2.6.0
pycparser              2.20
pydocstyle             5.0.2
pyflakes               2.2.0
pygame                 1.9.6
PyGithub               1.51
Pygments               2.6.1
PyJWT                  1.7.1
pylint                 2.5.3
PyMySQL                0.9.3
PyNaCl                 1.4.0
pynvim                 0.4.1
pyparsing              2.4.7
pypiwin32              223
PyQt5                  5.15.0
PyQt5-sip              12.8.0
PyQtWebEngine          5.15.0
pyrsistent             0.16.0
PySocks                1.7.1
pytest                 5.4.3
python-dateutil        2.8.1
python-jsonrpc-server  0.3.4
python-language-server 0.33.2
pytz                   2020.1
pywin32                228
pywin32-ctypes         0.2.0
pywinpty               0.5.7
pyzmq                  19.0.1
QDarkStyle             2.8.1
QtAwesome              0.7.2
qtconsole              4.7.4
QtPy                   1.9.0
questionary            1.5.2
readme-renderer        26.0
regex                  2020.6.8
requests               2.24.0
requests-oauthlib      1.3.0
requests-toolbelt      0.9.1
rfc3986                1.4.0
rope                   0.17.0
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             47.1.0
six                    1.15.0
snowballstemmer        2.0.0
sortedcontainers       2.2.2
soupsieve              2.0.1
sqlparse               0.3.1
stevedore              3.2.0
tabulate               0.8.7
terminado              0.8.3
testpath               0.4.4
tkScrolledFrame        1.0.4
toml                   0.10.1
tornado                6.0.4
tqdm                   4.48.2
traitlets              4.3.3
tweepy                 3.8.0
twine                  3.2.0
typed-ast              1.4.1
typing-extensions      3.7.4.2
urllib3                1.25.10
virtualenv             20.0.30
virtualenv-clone       0.5.4
virtualenvwrapper      4.8.4
watchdog               0.10.2
wcwidth                0.2.4
webencodings           0.5.1
wheel                  0.34.2
widgetsnbextension     3.5.1
wrapt                  1.12.1
zipp                   3.1.0
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```154 setup logging to NOTSET [DEBUG report:43]
200 find interpreter for spec PythonSpec(path=c:\python38\python.exe) [INFO builtin:44]
202 proposed PythonInfo(spec=CPython3.8.5.final.0-64, exe=c:\python38\python.exe, platform=win32, version='3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
202 accepted PythonInfo(spec=CPython3.8.5.final.0-64, exe=c:\python38\python.exe, platform=win32, version='3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:52]
206 symlink on filesystem does work [DEBUG info:47]
207 filesystem is not case-sensitive [DEBUG info:28]
279 create virtual environment via CPython3Windows(dest=E:\Programming_Python\Projects\Test_Project\.venv, clear=False, global=False) [INFO session:52]
279 create folder E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages [DEBUG _sync:25]
280 create folder E:\Programming_Python\Projects\Test_Project\.venv\Scripts [DEBUG _sync:25]
280 write E:\Programming_Python\Projects\Test_Project\.venv\pyvenv.cfg [DEBUG pyenv_cfg:34]
281     home = c:\python38 [DEBUG pyenv_cfg:38]
298     implementation = CPython [DEBUG pyenv_cfg:38]
299     version_info = 3.8.5.final.0 [DEBUG pyenv_cfg:38]
299     virtualenv = 20.0.30 [DEBUG pyenv_cfg:38]
299     include-system-site-packages = false [DEBUG pyenv_cfg:38]
299     base-prefix = c:\python38 [DEBUG pyenv_cfg:38]
299     base-exec-prefix = c:\python38 [DEBUG pyenv_cfg:38]
299     base-executable = c:\python38\python.exe [DEBUG pyenv_cfg:38]
300 symlink c:\python38\python.exe to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\python.exe [DEBUG _sync:44]
301 symlink c:\python38\pythonw.exe to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\pythonw.exe [DEBUG _sync:44]
301 symlink c:\python38\python3.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\python3.dll [DEBUG _sync:44]
302 symlink c:\python38\python38.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\python38.dll [DEBUG _sync:44]
302 symlink c:\python38\vcruntime140.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\vcruntime140.dll [DEBUG _sync:44]
303 symlink c:\python38\vcruntime140_1.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\vcruntime140_1.dll [DEBUG _sync:44]
303 symlink c:\python38\DLLs\libcrypto-1_1.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\libcrypto-1_1.dll [DEBUG _sync:44]
305 symlink c:\python38\DLLs\libffi-7.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\libffi-7.dll [DEBUG _sync:44]
305 symlink c:\python38\DLLs\libssl-1_1.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\libssl-1_1.dll [DEBUG _sync:44]
306 symlink c:\python38\DLLs\pyexpat.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\pyexpat.pyd [DEBUG _sync:44]
306 symlink c:\python38\DLLs\select.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\select.pyd [DEBUG _sync:44]
307 symlink c:\python38\DLLs\sqlite3.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\sqlite3.dll [DEBUG _sync:44]
307 symlink c:\python38\DLLs\tcl86t.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\tcl86t.dll [DEBUG _sync:44]
308 symlink c:\python38\DLLs\tk86t.dll to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\tk86t.dll [DEBUG _sync:44]
308 symlink c:\python38\DLLs\unicodedata.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\unicodedata.pyd [DEBUG _sync:44]
310 symlink c:\python38\DLLs\winsound.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\winsound.pyd [DEBUG _sync:44]
312 symlink c:\python38\DLLs\_asyncio.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_asyncio.pyd [DEBUG _sync:44]
314 symlink c:\python38\DLLs\_bz2.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_bz2.pyd [DEBUG _sync:44]
315 symlink c:\python38\DLLs\_ctypes.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_ctypes.pyd [DEBUG _sync:44]
316 symlink c:\python38\DLLs\_ctypes_test.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_ctypes_test.pyd [DEBUG _sync:44]
316 symlink c:\python38\DLLs\_decimal.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_decimal.pyd [DEBUG _sync:44]
317 symlink c:\python38\DLLs\_elementtree.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_elementtree.pyd [DEBUG _sync:44]
317 symlink c:\python38\DLLs\_hashlib.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_hashlib.pyd [DEBUG _sync:44]
318 symlink c:\python38\DLLs\_lzma.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_lzma.pyd [DEBUG _sync:44]
319 symlink c:\python38\DLLs\_msi.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_msi.pyd [DEBUG _sync:44]
319 symlink c:\python38\DLLs\_multiprocessing.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_multiprocessing.pyd [DEBUG _sync:44]
320 symlink c:\python38\DLLs\_overlapped.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_overlapped.pyd [DEBUG _sync:44]
321 symlink c:\python38\DLLs\_queue.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_queue.pyd [DEBUG _sync:44]
321 symlink c:\python38\DLLs\_socket.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_socket.pyd [DEBUG _sync:44]
322 symlink c:\python38\DLLs\_sqlite3.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_sqlite3.pyd [DEBUG _sync:44]
322 symlink c:\python38\DLLs\_ssl.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_ssl.pyd [DEBUG _sync:44]
323 symlink c:\python38\DLLs\_testbuffer.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_testbuffer.pyd [DEBUG _sync:44]
323 symlink c:\python38\DLLs\_testcapi.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_testcapi.pyd [DEBUG _sync:44]
324 symlink c:\python38\DLLs\_testconsole.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_testconsole.pyd [DEBUG _sync:44]
325 symlink c:\python38\DLLs\_testimportmultiple.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_testimportmultiple.pyd [DEBUG _sync:44]
326 symlink c:\python38\DLLs\_testmultiphase.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_testmultiphase.pyd [DEBUG _sync:44]
327 symlink c:\python38\DLLs\_tkinter.pyd to E:\Programming_Python\Projects\Test_Project\.venv\Scripts\_tkinter.pyd [DEBUG _sync:44]
329 create virtualenv import hook file E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\_virtualenv.pth [DEBUG api:94]
331 create E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\_virtualenv.py [DEBUG api:97]
332 ============================== target debug ============================== [DEBUG session:54]
333 debug via 'E:\Programming_Python\Projects\Test_Project\.venv\Scripts\python.exe' 'c:\python38\lib\site-packages\virtualenv\create\debug.py' [DEBUG creator:209]
332 {
  "sys": {
    "executable": "E:\\Programming_Python\\Projects\\Test_Project\\.venv\\Scripts\\python.exe",
    "_base_executable": "E:\\Programming_Python\\Projects\\Test_Project\\.venv\\Scripts\\python.exe",
    "prefix": "E:\\Programming_Python\\Projects\\Test_Project\\.venv",
    "base_prefix": "c:\\python38",
    "real_prefix": null,
    "exec_prefix": "E:\\Programming_Python\\Projects\\Test_Project\\.venv",
    "base_exec_prefix": "c:\\python38",
    "path": [
      "E:\\Programming_Python\\Projects\\Test_Project\\.venv\\Scripts\\python38.zip",
      "c:\\python38\\DLLs",
      "c:\\python38\\lib",
      "c:\\python38",
      "E:\\Programming_Python\\Projects\\Test_Project\\.venv",
      "E:\\Programming_Python\\Projects\\Test_Project\\.venv\\lib\\site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "cp1252"
  },
  "version": "3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]",
  "makefile_filename": "c:\\python38\\Lib\\config\\Makefile",
  "os": "<module 'os' from 'c:\\\\python38\\\\lib\\\\os.py'>",
  "site": "<module 'site' from 'c:\\\\python38\\\\lib\\\\site.py'>",
  "datetime": "<module 'datetime' from 'c:\\\\python38\\\\lib\\\\datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from 'c:\\\\python38\\\\lib\\\\json\\\\__init__.py'>"
} [DEBUG session:55]
430 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\dspta\AppData\Local\pypa\virtualenv) [INFO session:59]
435 got embed update of distribution pip from C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\embed\1\pip.json [DEBUG via_disk_folder:133]
438 got embed update of distribution pip from C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\embed\1\pip.json [DEBUG via_disk_folder:133]
440 got embed update of distribution wheel from C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\embed\1\wheel.json [DEBUG via_disk_folder:133]
441 got embed update of distribution setuptools from C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\embed\1\setuptools.json [DEBUG via_disk_folder:133]
443 got embed update of distribution wheel from C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\embed\1\wheel.json [DEBUG via_disk_folder:133]
443 got embed update of distribution setuptools from C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\embed\1\setuptools.json [DEBUG via_disk_folder:133]
445 install pip from wheel c:\python38\lib\site-packages\virtualenv\seed\wheels\embed\pip-20.2.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
446 install wheel from wheel c:\python38\lib\site-packages\virtualenv\seed\wheels\embed\wheel-0.34.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
446 Attempting to acquire lock 2546700429536 on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any.lock [DEBUG filelock:270]
447 Attempting to acquire lock 2546700430160 on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any.lock [DEBUG filelock:270]
447 install setuptools from wheel c:\python38\lib\site-packages\virtualenv\seed\wheels\embed\setuptools-49.2.1-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:53]
447 Lock 2546700429536 acquired on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any.lock [INFO filelock:274]
447 Lock 2546700430160 acquired on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any.lock [INFO filelock:274]
448 Attempting to acquire lock 2546700430736 on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any.lock [DEBUG filelock:270]
448 Attempting to release lock 2546700429536 on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any.lock [DEBUG filelock:315]
448 Attempting to release lock 2546700430160 on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any.lock [DEBUG filelock:315]
449 Lock 2546700430736 acquired on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any.lock [INFO filelock:274]
449 Lock 2546700429536 released on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any.lock [INFO filelock:318]
449 Lock 2546700430160 released on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any.lock [INFO filelock:318]
450 Attempting to release lock 2546700430736 on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any.lock [DEBUG filelock:315]
450 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any\pip to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\pip [DEBUG _sync:52]
451 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any\wheel to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\wheel [DEBUG _sync:52]
451 Lock 2546700430736 released on C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any.lock [INFO filelock:318]
452 copy C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any\easy_install.py to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\easy_install.py [DEBUG _sync:52]
454 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any\pkg_resources to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\pkg_resources [DEBUG _sync:52]
472 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any\wheel-0.34.2.dist-info to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\wheel-0.34.2.dist-info [DEBUG _sync:52]
477 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any\setuptools to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\setuptools [DEBUG _sync:52]
484 copy C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\wheel-0.34.2-py2.py3-none-any\wheel-0.34.2.virtualenv to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\wheel-0.34.2.virtualenv [DEBUG _sync:52]
491 generated console scripts wheel-3.8.exe wheel3.8.exe wheel3.exe wheel.exe [DEBUG base:48]
598 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any\setuptools-49.2.1.dist-info to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\setuptools-49.2.1.dist-info [DEBUG _sync:52]
606 copy C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-49.2.1-py3-none-any\setuptools-49.2.1.virtualenv to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\setuptools-49.2.1.virtualenv [DEBUG _sync:52]
615 generated console scripts easy_install.exe easy_install3.exe easy_install-3.8.exe easy_install3.8.exe [DEBUG base:48]
828 copy directory C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any\pip-20.2.1.dist-info to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\pip-20.2.1.dist-info [DEBUG _sync:52]
835 copy C:\Users\dspta\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-20.2.1-py2.py3-none-any\pip-20.2.1.virtualenv to E:\Programming_Python\Projects\Test_Project\.venv\Lib\site-packages\pip-20.2.1.virtualenv [DEBUG _sync:52]
838 generated console scripts pip3.exe pip3.8.exe pip-3.8.exe pip.exe [DEBUG base:48]
839 add activators for Bash, Batch, Fish, PowerShell, Python, Xonsh [INFO session:64]
846 write E:\Programming_Python\Projects\Test_Project\.venv\pyvenv.cfg [DEBUG pyenv_cfg:34]
847     home = c:\python38 [DEBUG pyenv_cfg:38]
847     implementation = CPython [DEBUG pyenv_cfg:38]
847     version_info = 3.8.5.final.0 [DEBUG pyenv_cfg:38]
847     virtualenv = 20.0.30 [DEBUG pyenv_cfg:38]
847     include-system-site-packages = false [DEBUG pyenv_cfg:38]
848     base-prefix = c:\python38 [DEBUG pyenv_cfg:38]
848     base-exec-prefix = c:\python38 [DEBUG pyenv_cfg:38]
848     base-executable = c:\python38\python.exe [DEBUG pyenv_cfg:38]
848 created virtual environment CPython3.8.5.final.0-64 in 700ms
  creator CPython3Windows(dest=E:\Programming_Python\Projects\Test_Project\.venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\dspta\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.2.1, setuptools==49.2.1, wheel==0.34.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:17]

```

**Comment by gaborbernat** [comment] 2020-08-20 22:27
Without a step by step reproducible this is hart to nail down. I've tried to replicate it but failed. We'll need a step by step method to be able to fix it and understand it. By the looks it seems as we extend the prompt multiple times, hard to tell without being able to reproduce it. I'll close this now, but feel free to submit a how to reproduce it and we'll reopen it.

**Closed by gaborbernat** 2020-08-20 22:27 UTC
Labels: bug

**Comment by pfmoore** [comment] 2020-08-21 06:45
Oh-my-posh has its own virtualenv detection which adds the environment to the prompt. The activate script adds it as well.

You should set `$env:VIRTUAL_ENV_DISABLE_PROMPT = "yes"` to tell the activate script not to modify the prompt.

**Comment by gaborbernat** [comment] 2020-08-21 06:47
> Oh-my-posh has its own virtualenv detection which adds the environment to the prompt. The activate script adds it as well.

Tested it locally and I don't think that's what's happening here because the prompt seems to be completly replaced with our version 🤔 https://github.com/pypa/virtualenv/blob/master/src/virtualenv/activation/powershell/activate.ps1#L49

**Comment by pfmoore** [comment] 2020-08-21 06:58
That code 

```powershell
    if ("__VIRTUAL_PROMPT__" -ne "") {
        function global:prompt {
            # Add the custom prefix to the existing prompt
            $previous_prompt_value = & $function:_old_virtual_prompt  # Call old prompt function
            ("__VIRTUAL_PROMPT__" + $previous_prompt_value)  # Return our value followed by original prompt
        }
```

creates a new prompt function that calls the old prompt function to get its value, then appends that value to our new value and returns the result.

The solution I posted works for me with a custom prompt, and I'm pretty sure it worked when I previously used oh-my-posh. I'll try to test again later, to confirm.
