### ISSUE TITLE
Wheel for virtualenv-15.0.3 contains old versions of pip, setuptools and wheel

### ISSUE THREAD

**Issue by rlamy** [pypa/virtualenv#960] opened 2016-09-27 15:06 UTC
```
~/dev/stuff$ unzip -l virtualenv-15.0.3-py2.py3-none-any.whl 
Archive:  virtualenv-15.0.3-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    98983  2016-08-05 12:22   virtualenv.py
  1198961  2016-08-05 09:30   virtualenv_support/pip-8.1.2-py2.py3-none-any.whl
  1188805  2016-01-28 12:30   virtualenv_support/pip-8.0.2-py2.py3-none-any.whl
        0  2015-02-22 23:17   virtualenv_support/__init__.py
   472181  2016-01-31 21:58   virtualenv_support/setuptools-19.6.2-py2.py3-none-any.whl
    63454  2016-01-28 12:30   virtualenv_support/wheel-0.26.0-py2.py3-none-any.whl
    66878  2016-08-05 09:30   virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl
   510116  2016-08-05 09:30   virtualenv_support/setuptools-22.0.5-py2.py3-none-any.whl
    23000  2016-01-28 12:30   virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl
     2011  2016-08-05 12:44   virtualenv-15.0.3.dist-info/DESCRIPTION.rst
       48  2016-08-05 12:44   virtualenv-15.0.3.dist-info/entry_points.txt
     1151  2016-08-05 12:44   virtualenv-15.0.3.dist-info/metadata.json
       30  2016-08-05 12:44   virtualenv-15.0.3.dist-info/top_level.txt
      110  2016-08-05 12:44   virtualenv-15.0.3.dist-info/WHEEL
     2834  2016-08-05 12:44   virtualenv-15.0.3.dist-info/METADATA
     1565  2016-08-05 12:44   virtualenv-15.0.3.dist-info/RECORD
---------                     -------
  3630127                     16 files
```

Note the duplicate entries for pip, setuptools and wheel. 

As a consequence, a virtualenv installed from this wheel is incompatible with pypy3-v5.2.0, because it will pick up pip-8.0.2 instead of pip-8.1.2.

Given that the source distribution only has the more recent versions, I assume that the duplication was unintentional.

**Comment by pfmoore** [comment] 2016-09-27 15:21
Confirmed, I can see the same duplicate entries in my installation. However, I'm surprised if this is resulting in pip 8.0.2 being installed, as the latest version present should be installed.

So:

1. This is unnecessarily bloating the virtualenv wheel, so agreed it should be fixed, but
2. Can you provide more information on how to demonstrate pip 8.0.2 being installed as a result? On my (Windows, CPython 3.5) installation, it installs the latest versions as expected.

**Comment by rlamy** [comment] 2016-09-27 15:32
I don't think it installs pip 8.0.2, however it uses it when creating the virtualenv, which is a problem when trying to create a pypy3 virtualenv, because only 8.1.2 supports pypy3.

**Comment by pfmoore** [comment] 2016-09-27 16:30
Ah, so it picks the 8.0.2 version to run to do the install. Yes that would cause the issue. As you noted, it seems to be a packaging issue rather than a code issue, so it should get sorted when we next release.

**Closed** 2019-01-21 22:22 UTC
Labels: wontfix
