### ISSUE TITLE
virtualenv-1.13.2 fails to create a virtual environment with pypy-2.6.0

### ISSUE THREAD

**Issue by erosennin** [pypa/virtualenv#790] opened 2015-08-28 10:32 UTC
```
$ virtualenv -p pypy /tmp/testenv
Running virtualenv with interpreter /usr/bin/pypy
New pypy executable in /tmp/testenv/bin/pypy
Please make sure you remove any previous custom paths from your /home/and/.pydistutils.cfg file.
Installing setuptools, pip, wheel...
  Complete output from command /tmp/testenv/bin/pypy -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Collecting wheel
Installing collected packages: setuptools, pip, wheel
Exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/wheel.py", line 465, in move_wheel_files
    generated.extend(maker.make(spec))
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 353, in make
    self._make_script(entry, filenames, options=options)
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 257, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 231, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/usr/lib64/python2.7/site-packages/virtualenv_support/pip-7.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/util.py", line 388, in write_binary_file
    with open(path, 'wb') as f:
IOError: [Errno 13] Permission denied: '/usr/bin/easy_install'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "/usr/lib64/python2.7/site-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/usr/lib64/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib64/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib64/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/testenv/bin/pypy -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2
```

**Comment by ramnes** [comment] 2015-10-27 10:29
I'm hit by that issue too. I have exactly the same stack trace.

**Comment by ultrabug** [comment] 2015-10-27 11:06
:+1:

**Comment by meatballcoder** [comment] 2015-10-30 18:21
Anyone have an answer?

**Comment by rsommer** [comment] 2015-11-18 09:25
Does also affect pypy 4.0 for me.

**Comment by KenetJervet** [comment] 2015-11-20 10:03
Any update? This issue is *EXTREMELY DANGEROUS*. I'm using Gentoo and I did `sudo virtualenv -p pypy ...` and my system is in a complete mess. All python-related scripts, under /usr/bin, are fucked up. I can't even reinstall them because all my portage-related scripts are fucked up too. They are all soft-linked to /usr/lib/python-exec/python-exec2, and this file is rewritten to do pip.main() WHAT A DISASTER!!!

**Comment by ramnes** [comment] 2015-11-20 10:44
@KenetJervet, I experimented that issue on Gentoo also. You can fix everything by just reinstalling python-exec with `/usr/lib/python-exec/python3.3/emerge -av python-exec`. Good luck!

**Comment by btall** [comment] 2015-11-20 11:52
:+1:

**Comment by KenetJervet** [comment] 2015-11-20 13:39
@ramnes myeah that's what someone told me on IRC also. Thanks for your help!

**Comment by mamrhein** [comment] 2015-11-23 15:49
On Gentoo this is caused by a patch (1.9-scripts-location.patch):
    --- a/lib-python/2.7/distutils/command/install.py
    +++ b/lib-python/2.7/distutils/command/install.py
    @@ -87,7 +87,7 @@
             'purelib': '$base/site-packages',
             'platlib': '$base/site-packages',
             'headers': '$base/include',
    -        'scripts': '$base/bin',
    +        'scripts': '/usr/bin',
             'data'   : '$base',
             },
         }
You can change that line in /usr/lib/pypy/lib-python/2.7/distutils/command/install.py back to "    'scripts': '$base/bin'," in order to make virtualenv work under pypy.
But beware that scripts will then end-up in /usr/lib/pypy/bin if you install packages into the system pypy!!!

**Comment by ultrabug** [comment] 2015-11-26 14:04
ping @mgorny in case you didn't know about this

**Comment by mgorny** [comment] 2015-11-26 14:14
I still don't have any real patch to fix this. If I revert the patch I inherited, we can as well disable PyPy on all packages. We really need a proper fix there but that requires someone capable of fiddling with PyPy internals and having some time — and for a few years already, we have seen noone willing to do that. As I see it, PyPy is a dead end right now.

**Comment by ultrabug** [comment] 2015-11-27 09:59
@mgorny thanks for your quick reply and answer. I'm not sure what we really need from the PyPy guys since I have to admit I didn't take a proper look at the core of the problem... cheers.

**Comment by mgorny** [comment] 2015-11-28 08:16
I've committed an attempted fix yesterday. It's a bit ugly but makes sure gentoo hackery applies only to system-wide installs (when install_base is /usr/lib*/pypy).

**Comment by mamrhein** [comment] 2015-11-28 13:26
Works perfect for me.
Thank you!!!

**Comment by ultrabug** [comment] 2015-12-06 09:49
@mgorny thanks a lot !

ping @ramnes and @KenetJervet for feedback too if possible ? :)

**Closed** 2019-01-22 00:01 UTC
Labels: wontfix
