### ISSUE TITLE
Cyrillic in the path of files. Invalid encoding.

### ISSUE THREAD

**Issue by ArTyGill** [pypa/virtualenv#1375] opened 2019-07-04 22:14 UTC
OS: Windows 10
Locale: ru-Ru
Python: 3.7.3
Virtualenv version: latest.
Username of PC: 'Артем' - It's cyrillic string in encoding 'windows-1251'

When trying to configure vitualenv, a path mismatch error occurs for UTF-8

```
Installing setuptools, pip, wheel...
done.
Traceback (most recent call last):
  File "C:\Users\Артем\AppData\Roaming\Python\Python37\site-packages\virtualenv.py", line 931, in call_subprocess
    line = line.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 27: invalid start byte
```

_As you can see, the problem is that the username is given by the Cyrillic and this can only be corrected by major changes to the system._

In windows, paths are encoded in UTF-16 and windows-1251 (according to data from wikipedia).
In virtualenv.py, decoding by encoding occurs first using the file encoding (UTF-8), and then failing, the file system encoding must be windows-1251, but sys.getfilesystemencoding() returns utf-8 again.

If we replace line 933 in virtualenv.py with an exception (listed below), then everything works fine.

```
try: 
    line = line.decode(fs_encoding)
except UnicodeDecodeError:
    line = line.decode('cp1251')
```

I think the developers of the SYS module or the developers of VIRTUALENV need to add processing locale and language installed on the computer.

**Comment by gaborbernat** [comment] 2019-12-28 09:43
Duplicate of https://github.com/pypa/virtualenv/issues/457

**Closed by gaborbernat** 2019-12-28 09:43 UTC
Labels: rewrite
