### ISSUE TITLE
Pip fails with space in virtualenv path

### ISSUE THREAD

**Issue by mnm678** [pypa/virtualenv#994] opened 2016-12-08 02:47 UTC
Failed to execute process '/Users/.../venv/bin/pip'. Reason:
The file '/Users/.../venv/bin/pip' does not exist or could not be executed.

python 2.7 installed via homebrew
virtualenv installed via pip

**Comment by yan12125** [comment] 2016-12-10 07:53
Both Apple's XNU kernel [1] and Linux [2] cuts off interpreter name at the first whitespace. In other words, paths with whitespaces (' ' 0x20 and '\t' 0x09) can't work correctly. I suggest virtualenv forbid such paths.

[1] https://github.com/opensource-apple/xnu/blob/10.11/bsd/kern/kern_exec.c#L532-L535
[2] https://github.com/torvalds/linux/blob/v4.9-rc8/fs/binfmt_script.c#L60-L68

**Comment by yan12125** [comment] 2016-12-10 12:45
Seems this issue is identical to https://github.com/pypa/pip/issues/923

**Comment by batmanav** [comment] 2017-01-07 16:35
+1. I'm also facing this issue.

**Comment by JDLH** [comment] 2017-02-25 07:23
This looks to me like a duplicate of #53 "Whitespace in root path of virtualenv breaks scripts". 
I want to repeat the comment from https://github.com/pypa/virtualenv/issues/997#issuecomment-270681253, "virtualenv are broken with fragile kernel shebang parsing."  And in that spirit, #1014 "Not compatible with a directory having emojis in its path" is another example of virtualenv being broken by fragile kernel shebang parsing.  I'll bet the problem occurs with any non-ASCII characters in the path, I'll bet.

Maybe we should collect all three aspects of fragile kernel shebang parsing into one issue, so that we can be sure that one fix can address spaces, length, and non-ASCII characters?  I nominate #53, because it's the oldest.

**Comment by gaborbernat** [comment] 2019-01-15 10:15
You are right, thanks!

**Closed by gaborbernat** 2019-01-15 10:15 UTC
