### ISSUE TITLE
Long env path names cause weird errors after activiting virtual environment

### ISSUE THREAD

**Issue by HaraldNordgren** [pypa/virtualenv#997] opened 2017-01-05 15:37 UTC
After creating a virtualenv in the path

`/home/harald/git-repos/sandbox/stackoverflow/41454203-how-do-you-import-the-library-being-tested-when-running-a-nosetest/env`

I could not run the env's pip,

```
nosetest/env$ ./bin/pip
bash: ./bin/pip: /home/harald/git-repos/sandbox/stackoverflow/41454203-how-do-you-import-the-l: bad interpreter: Permission denied
```

and running just pip gives me the system's pip, with all of its packages.

**Comment by yan12125** [comment] 2017-01-05 16:06
Not virtualenv's fault. Shebangs have length limits, see http://www.in-ulm.de/~mascheck/various/shebang/.

This is basically a duplicate of #994 - virtualenv are broken with fragile kernel shebang parsing.

**Comment by HaraldNordgren** [comment] 2017-01-05 16:34
Where is the shebang written to file?

And is there maybe some workaround we could employ to make virtual environments more sturdy?

**Comment by yan12125** [comment] 2017-01-05 16:54
> Where is the shebang written to file?

Do you mean the location of the shebang or the codes that generate a shebang? 1. In the first line of the file ```bin/pip``` 2. In [distlib](https://bitbucket.org/pypa/distlib/src/f702f6afc1d03717fa88a742b9fb99bedd599ff2/distlib/scripts.py?at=default&fileviewer=file-view-default#scripts.py-139)

> And is there maybe some workaround we could employ to make virtual environments more sturdy?

I don't think there are simple workarounds. A possibility is writing a user space shebang parser just like py.exe on Windows.

**Comment by HaraldNordgren** [comment] 2017-01-05 17:52
Using pip as an example, one thing we could do is move the current `pip` to `.pip`, remove the shebang line and create a new `pip` file with the following content:

```
#!/bin/bash
/path/to/env/bin/python3 /path/to/env/bin/.pip $@
```

Basically, wrap the programs in shell scripts calling the original file to get around the problem of long shebangs.

By quoting the paths we could probably solve the problem with spaces as well.

**Comment by yan12125** [comment] 2017-01-06 10:05
OK maybe my definition for "workarounds" is too strict. I thought it shouldn't break existing things. In this case, using /bin/bash usually works but not always. Some systems do not install bash in /bin/ (FreeBSD install it at /usr/local/bin/bash), and some systems do not provide bash at all. (Most Android uses /system/bin/sh)

A similar idea was proposed 3 years ago: https://github.com/pypa/pip/issues/923#issuecomment-19655227. Apparently no PyPA core developers are interested in this approach :(

**Comment by HaraldNordgren** [comment] 2017-01-06 12:33
No, you're right. The workaround shouldn't break things. As long as `env` lives in the same place in every Unix system, this should work just as well:

    #!/usr/bin/env sh
    "/path/to/env/bin/python" "/path/to/env/bin/.pip" $@

It's nice to see that someone else brought up the same idea. However, @cellularmitosis phrased in negative terms back then, so it only makes sense that no one took it seriously. It doesn't seem like any of the developers actually commented on it.

Let us give it a positive spin this time around and present it as waterproof solution to long paths and spaces. I'm not exactly sure how I would go about to putting this in the virtualenv source code though.

**Comment by yan12125** [comment] 2017-01-06 14:59
Looks better. If it's possible to use a single file, I believe it will be ready for a pull request!

**Comment by HaraldNordgren** [comment] 2017-01-09 02:51
@yan12125 I created a pull request.

**Comment by vsajip** [comment] 2017-05-28 15:35
I've updated `distlib` to handle long paths and paths with spaces. I didn't use Harald Nordgren's patch directly (it had some problems - e.g. no tests) but the approach is the same - using '/bin/sh' as the executable. `pip` / `virtualenv` maintainers might want to test after locally vendoring the current version of the `distlib` repository.

**Comment by cellularmitosis** [comment] 2017-05-28 20:40
@HaraldNordgren ah, I should have been clearer that my dismay was directed at Apple, not at the virtualenv guys!  On Linux, this isn't an issue at all, and I had assumed this was an insurmountable shortcoming of OS X shebang parsing.  Glad to see there's a solution!

**Comment by Imaskar** [comment] 2020-02-11 14:28
Is it really fixed? 
I just run into the same issue using latest pip 20.0.2 and virtualenv 20.0.1 and python 3.7.4 . And it still generates the long path.

**Comment by gaborbernat** [comment] 2020-02-11 14:58
It seems here we've regressed as we're not using ``distlib`` to generate the paths.

**Closed** 2020-02-11 17:41 UTC

**Comment by gaborbernat** [comment] 2020-02-11 18:22
Hello, a fix for this issue has been released via virtualenv 20.0.2; see https://pypi.org/project/virtualenv/20.0.2/ (https://virtualenv.pypa.io/en/latest/changelog.html#v20-0-2-2020-02-11) . Please give a try and report back if your issue has not been addressed; if not, please comment here, and we'll reopen the ticket. We want to apologize for the inconvenience this has caused you and say thanks for having patience while we resolve the unexpected bugs with this new major release.

![thanks](https://media.tenor.co/images/1114067881329bb4218880eeb7ec34fd/tenor.gif)

**Comment by Imaskar** [comment] 2020-02-13 12:40
Thank you for acting quick!
I tried 20.0.2 and it worked. It generates full shebang on macOS which supports long paths, and short on Linux.

**Comment by MartinKosicky** [comment] 2020-04-01 17:53
Well instead of pip... you can use python -m pip.  That helped me

**Comment by gaborbernat** [comment] 2020-04-01 17:54
@MartinKosicky you can, but should no longer be needed.

**Comment by MartinKosicky** [comment] 2020-04-01 17:57
Ok I am a bit confused. I am using venv probabbly and that is why I can't see this fix.  This is virtualenv, which is something else?

**Comment by gaborbernat** [comment] 2020-04-01 17:59
Yeah, we're very much different from venv. One advantage of using virtualenv is that we can fix issues faster than venv. There's more detail on differences here https://github.com/pypa/virtualenv/issues/1366#issue-454109948

**Comment by MartinKosicky** [comment] 2020-04-01 18:02
very hard to google something about virtualenv because it always gives me venv... even the standard python pages call it virtualenv, but the module is called venv :D

**Comment by gaborbernat** [comment] 2020-04-01 18:04
IMHO it should be calling it virtual environments, not virtualenv. If you find virtualenv in venv doc then probably open an issue under http://bugs.python.org/
