### ISSUE TITLE
virtualenv does not copy all Python2.7/Lib files

### ISSUE THREAD

**Issue by MaheshVenkateshwaran1203** [pypa/virtualenv#1214] opened 2018-10-15 14:44 UTC
I am trying to create a virtualenv for a specific pthon version (python2.7.10).
However, during deployment inside a container, I get a import error for pip (__future__ not found)
I see that during the virtualenv creation, system libraries are not copied.
Am I missing something? 

Steps

sudo -H pip install virtualenv
cd /app_path
mkdir my_tmp
cd my_tmp
wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
tar -zxvf Python-2.7.10.tgz
cd Python-2.7.10
./configure --prefix=/app_path/my_tmp/.localpython
make
make install
cd /app_path
virtualenv --always-copy --system-site-packages venv -p  my_tmp/.localpython/bin/python2.7

__future__.py is present in the source directory where python was installed

ls my_tmp/Python-2.7.10/Lib/__future__.py
my_tmp/Python-2.7.10/Lib/__future__.py

However the same is not there inside the venv.

ls venv/lib/python2.7/
_abcoll.py   codecs.pyc    encodings        lib-dynload    ntpath.py        posixpath.pyc  site.pyc           sre_parse.py   types.py      warnings.pyc
_abcoll.pyc  config        fnmatch.py       linecache.py   orig-prefix.txt  re.py          sre_compile.py     sre_parse.pyc  types.pyc     _weakrefset.py
abc.py       copy_reg.py   fnmatch.pyc      linecache.pyc  os.py            re.pyc         sre_compile.pyc    sre.py         UserDict.py   _weakrefset.pyc
abc.pyc      copy_reg.pyc  genericpath.py   locale.py      os.pyc           site-packages  sre_constants.py   stat.py        UserDict.pyc
codecs.py    distutils     genericpath.pyc  locale.pyc     posixpath.py     site.py        sre_constants.pyc  stat.pyc       warnings.py

virtualenv --version
16.0.0

**Comment by pfmoore** [comment] 2018-10-15 15:06
This is by design. A virtualenv is not intended for use without the source Python present - we only copy a subset of the system site-packages. Are you trying to create a virtualenv and then use it in a situation where the main Python interpreter isn't available?

**Comment by MaheshVenkateshwaran1203** [comment] 2018-10-15 15:14
thats correct. my main python in ubuntu is 2.7.12. However I want to use python2.7.10 for all my applications. hence the virtualenv.
When I try to use pip inside the virtualenv, I get the error no module named __future__

Separate question, Is it possible to install python2.7.10 or lower version of python using apt-get?

**Comment by pfmoore** [comment] 2018-10-15 15:38
That's not something you can do with virtualenv. It's for creating an isolated environment based on your existing Python version, not for managing other versions of Python.

> Is it possible to install python2.7.10 or lower version of python using apt-get?

I don't know, sorry, I don't use Ubuntu. Someone else may be able to help with that.

**Comment by gaborbernat** [comment] 2018-10-27 18:43
There's a big price to pay for that kind of flexibility, and virtualenvs goal is to be a lightweight tool. If you want full python environment and not just a virtualenv of an existing one you're encouraged to install those python versions separately. You have the option of installing python with the main installer downloaded from python.org, pyenv, conda or anyway else. Creating full python copies is out of scope for virtualenv.

**Closed by gaborbernat** 2018-10-27 18:43 UTC
