### ISSUE TITLE
PowerShell compatability broken

### ISSUE THREAD

**Issue by OverlordQ** [pypa/virtualenv#669] opened 2014-11-13 18:03 UTC
Trying to activate in PowerShell no longer works:
# 

``````
PS C:\Python27\Scripts> .\virtualenv.exe dev
New python executable in dev\Scripts\python.exe
Installing setuptools, pip...done.
PS C:\Python27\Scripts> .\dev\Scripts\activate.ps1
File C:\Python27\Scripts\dev\Scripts\activate.ps1 cannot be loaded. The contents of file C:\Python27\Scripts\dev\Scripts\activate.ps1 may have been tampered because the hash of the file does not match the hash stored in the digital signature. The script will not execute on the system. Please see "get-help about_signing" for more details..
At line:1 char:27
+ .\dev\Scripts\activate.ps1 <<<<
    + CategoryInfo          : NotSpecified: (:) [], PSSecurityException
    + FullyQualifiedErrorId : RuntimeException```
===
``````

**Comment by Ivoz** [comment] 2015-01-01 18:07
@pfmoore you know how script signing works on windows? We want to either document it or remove it, one way or another, so something doesn't become "untouchable".

**Comment by pfmoore** [comment] 2015-01-01 18:21
As I said, only @jezdez is able to sign this, AFAIK, as he has the key. Also, you need to sign the script using Powershell (or at least that's how the help says to do it). I could copy the relevant help into a document, but without a cert file and a Powershell environment, it's not a huge amount of help.

Personally, I'd say we drop the signature altogether. I think it's just a case of deleting the ```SIG``` block at the end, but as I can't reproduce the issue I can't confirm that. @OverlordQ if you remove that whole comment block at the end, does that fix the issue?

**Comment by Ivoz** [comment] 2015-01-01 18:33
Did jezdez get his key specially signed by microsoft, or does the check just want a valid signature or no signature?

**Comment by dstufft** [comment] 2015-01-01 21:52
As I understand it if you don't have the file signed powershell won't run it by default unless you allow unsigned files. The code signing key just needs to come from a reputable place like startssl.com or digicert or whatever.

**Comment by amrarnous** [comment] 2017-04-21 08:01
Just Set The Execution Policy To Unrestricted
and Here is a toutrial
http://www.techotopia.com/index.php/Windows_PowerShell_1.0_Security

**Comment by franklinyu** [comment] 2018-09-17 20:09
The signature is clearly outdated and can be verified with [`Get-AuthenticodeSignature`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-authenticodesignature).

```text
SignerCertificate                           Status          Path
-----------------                           ------          ----
AA3BDD2F620B9C8ED8DFEAB9BE92C5D888FF674C    HashMismatch    activate.ps1
```

**Comment by gaborbernat** [comment] 2018-10-31 14:49
@pfmoore I suppose we can change the certificate and re-sign it, as fix for this long outstanding issue

**Comment by pfmoore** [comment] 2018-10-31 15:26
I still say just drop the signature. We don't have the infrastructure to sign scripts, and it's not as if it adds any useful safety (after all, nothing else is signed).

**Comment by franklinyu** [comment] 2018-10-31 18:06
Agree. A reasonable developer would set execution polity to `RemoteSigned`, so signature is verified for anything downloaded *from browser* (insecure context), but in the same time VirtualEnv is not affected because things downloaded by Python is treated as local file. So I think we can remove the signature and tell users to

```powershell
Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy RemoteSigned
```

**Comment by gaborbernat** [comment] 2018-11-06 17:45
We'll remove signature, tracked by #816

**Closed by gaborbernat** 2018-11-06 17:45 UTC
Labels: bug
