### ISSUE TITLE
imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by dendisuhubdy** [pypa/virtualenv#1191] opened 2018-07-09 14:04 UTC
```
Using /usr/local/bin/python3.7m (3.7.0) to create virtualenv...
⠋Running virtualenv with interpreter /usr/local/bin/python3.7m
Using base prefix '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7'
/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```

**Comment by gregfitch** [comment] 2018-07-12 16:33
https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L1040-L1069
https://docs.python.org/3/library/imp.html#imp.find_module

**Comment by AvdN** [comment] 2018-07-28 05:15
Duplicate of #555 and #955

**Comment by kylemart** [comment] 2018-09-22 03:19
> https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L1040-L1069
> https://docs.python.org/3/library/imp.html#imp.find_module

Based off of the links you shared, it seems as though this warning is expected behavior for newer versions of Python then. Is that a correct interpretation? Should I just ignore the warning? @gregfitch

**Comment by gaborbernat** [comment] 2018-10-03 16:41
For now, just ignore, will be fixed in a future version of virtualenv and tracked by #955.

**Closed by gaborbernat** 2018-10-03 16:41 UTC

**Comment by pfmoore** [comment] 2018-10-31 13:08
@gaborbernat #955 is about the embedded distutils, whereas this is about the virtualenv script itself - so this issue occurs every time virtualenv is used, while #955 is relatively rare (or at least, I've never seen it occur).

I suggest that as an interim fix we suppress the deprecation warning - see #1238
