### ISSUE TITLE
Windows embeddable throws FileNotFoundError

### ISSUE THREAD

**Issue by zerocewl** [pypa/virtualenv#2368] opened 2022-06-27 10:22 UTC
**Issue**

Using the latest (`20.15.0`) version of `virtualenv` together with python 3.9 [Windows embeddable package](https://www.python.org/ftp/python/3.9.13/python-3.9.13-embed-amd64.zip) throws a `FileNotFoundError` if calling any module code e.g. `python.exe -m virtualenv testEnv`.

While following the issue [Windows embedable support #1774](https://github.com/pypa/virtualenv/issues/1774) and the depending MR [Windows embedable support](https://github.com/pypa/virtualenv/pull/2353) i though it should now be possible to create and handle any `venv` with a windows embeddable python, but after proceeding the [mentioned steps](https://github.com/pypa/virtualenv/issues/1774#issuecomment-619170133) i was still not able to use the `virtualenv` module. Am i missing any step?

> I unzipped the embedded package: https://www.python.org/ftp/python/3.9.13/python-3.9.13-embed-amd64.zip
> Then I run the get-pip.py: https://bootstrap.pypa.io/get-pip.py
> Then I uncomment in python39._pth the import statement.
> Then I add some path to PATH env variable. (add path to python.exe and pip.exe)
> Then I run pip install virtualenv.
Then I tried to call `python.exe -m virtualenv testEnv`

Note: the unzipped `python` folder does not contain any `DLLs` subfolder.

(Tested with latest python `3.9` and `3.10`.)

**Environment**

Provide at least:
- OS:

````sh
C:\Users\tester\Downloads\python-3.9.13-embed-amd64>systeminfo

Host Name:                 WIN10
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
...
````

- ``pip list`` of the host python where ``virtualenv`` is installed:

 ```console
C:\Users\tester\Downloads\python-3.9.13-embed-amd64>python -m pip list
Package      Version
------------ -------
distlib      0.3.4
filelock     3.7.1
pip          22.1.2
platformdirs 2.5.2
setuptools   62.6.0
six          1.16.0
virtualenv   20.15.0
wheel        0.37.1
 ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console

C:\Users\tester\Downloads\python-3.9.13-embed-amd64>python.exe -m virtualenv testENV --vvv --with-traceback
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\__main__.py", line 80, in <module>
    run_with_catch()  # pragma: no cov
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\__main__.py", line 65, in run_with_catch
    run(args, options, env)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\__main__.py", line 18, in run
    session = cli_run(args, options, env)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\run\__init__.py", line 30, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\run\__init__.py", line 48, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\run\__init__.py", line 74, in build_parser
    CreatorSelector(interpreter, parser),
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\run\plugin\creators.py", line 15, in __init__
    creators, self.key_to_meta, self.describe, self.builtin_key = self.for_interpreter(interpreter)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\run\plugin\creators.py", line 25, in for_interpreter
    meta = creator_class.can_create(interpreter)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 34, in can_create
    cls._sources_can_be_applied(interpreter, meta)
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 39, in _sources_can_be_applied
    for src in cls.sources(interpreter):
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py", line 67, in sources
    for ref in refs:
  File "C:\Users\tester\Downloads\python-3.9.13-embed-amd64\lib\site-packages\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py", line 98, in dll_and_pyd
    for file in folder.iterdir():
  File "pathlib.py", line 1160, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\tester\\Downloads\\python-3.9.13-embed-amd64\\DLLs'
```

**Comment by reksar** [comment] 2022-06-27 14:25
Creating an empty `DLLs` folder should fix the issue.

**Comment by reksar** [comment] 2022-06-27 15:39
I can't to find the difference between 3.9 and 3.10 behaviors. Note that in the embeddable Python std lib is zipped and you have problem with `zipimporter` during importing std `datetime` module from `python39.zip`. I guess. So the issue is predictable, but why only for 3.9? Maybe 3.10 tries to import from elsewhere? You can test Python paths by adding the `<local venv dir>\Scripts\python39(310)._pth` file. Take the `python*._pth` file from Python host dir as example.

**Comment by reksar** [comment] 2022-06-27 16:19
Ha! [Deprecated since Python 3.10. Use exec_module() instead.](https://github.com/python/cpython/blob/117217245390ed3e6fe166180f052e022d296921/Lib/zipimport.py#L279)

**Comment by zerocewl** [comment] 2022-06-27 17:37
> Ha! [Deprecated since Python 3.10. Use exec_module() instead.](https://github.com/python/cpython/blob/117217245390ed3e6fe166180f052e022d296921/Lib/zipimport.py#L279)
> 
> It seems you need to add a hack for old `zipimporter` if you want to support old versions of embeddable Python in your project.

Maybe this can be added to the docs? 🤔

**Comment by reksar** [comment] 2022-06-27 17:57
Hm, where exactly? Looks like everything is in place.

[The embeddable package](https://docs.python.org/3/using/windows.html#the-embeddable-package)

> The standard library is included as pre-compiled and optimized .pyc files in a ZIP

[zipimport](https://docs.python.org/3/library/zipimport.html?#zipimport.zipimporter.load_module)

> Deprecated since version 3.10: Use [exec_module()](https://docs.python.org/3/library/zipimport.html?#zipimport.zipimporter.exec_module) instead.

**Comment by zerocewl** [comment] 2022-06-28 07:12
Sry i thought `virtualenv` will only work with embedded python >= 3.10, but i found the depending issue in the dateparser repo.

Before `python3.10` the `exec_module()` was missing.

https://github.com/scrapinghub/dateparser/issues/849

**Comment by reksar** [comment] 2022-06-28 07:38
Yes, this is not a virtualenv problem.

But initially you got the error because the `DLLs` dir was missing. I think, the virtualenv should take care of it during setup. 👍

**Comment by zerocewl** [comment] 2022-06-28 09:29
Maybe ignore only if embedded python is used? In the other case the error would you point to the right direction.

**Comment by reksar** [comment] 2022-06-28 18:08
@pfmoore Call it a non-standard use case if you like)

All we do is:
* copy one extra **zip** file if it exists
* do not crash with an error if the `DLLs` dir if it does not exists

**Comment by gaborbernat** [comment] 2022-06-29 00:11
The PR has been now merged.

**Closed by gaborbernat** 2022-06-29 00:11 UTC
Labels: bug
