### ISSUE TITLE
--python arg broken on Windows 10 between 20.0.33 and 20.0.34?

### ISSUE THREAD

**Issue by thorbjornwolf** [pypa/virtualenv#1988] opened 2020-10-19 15:23 UTC
**Issue**

I'm using tox, which in turn is using virtualenv.
Ignoring tox and focusing on virtualenv, I run this command (derived from what fails in tox):

```
python -m virtualenv --no-download --python C:\redacted\python.exe .package
```
with "C:\redacted" being un-redacted on my machine.

With virtualenv 20.0.33, the command runs successfully: An environment gets created.

With virtualenv 20.0.34 and 20.0.35, the command breaks with the following

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\redacted\\python.exe'
```

**Environment**

Using miniconda with conda to create the super-environment, and conda to install tox and specific versions of virtualenv: `conda install virtualenv==20.0.33 -y`

- OS: Windows 10  :( 
- ``pip list`` of the host python where ``virtualenv`` is installed:

```console
Package            Version
------------------ -------------------
appdirs            1.4.4
certifi            2020.6.20
colorama           0.4.3
distlib            0.3.1
filelock           3.0.12
importlib-metadata 1.7.0
packaging          20.4
pip                20.2.3
pluggy             0.13.1
py                 1.9.0
pyparsing          2.4.7
setuptools         50.3.0.post20201006
six                1.15.0
toml               0.10.1
tox                3.15.0
virtualenv         20.0.34     <---- and 33 and 35
wheel              0.35.1
wincertstore       0.2
zipp               3.3.0
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

Broken run (with .34)
```console
(my-miniconda-env) PS C:\redacted> python -m virtualenv --no-download --python C:\redacted\python.exe .package -vvv --with-traceback

159 setup logging to NOTSET [DEBUG report:43]
172 find interpreter for spec PythonSpec(path=C:\redacted\python.exe) [INFO builtin:44]
173 proposed PythonInfo(spec=CPython3.7.9.final.0-64, exe=C:\redacted\python.exe, platform=win32, version='3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
174 accepted PythonInfo(spec=CPython3.7.9.final.0-64, exe=C:\redacted\python.exe, platform=win32, version='3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:52]
179 symlink on filesystem does not work [DEBUG info:47]
180 filesystem is not case-sensitive [DEBUG info:28]
271 create virtual environment via CPython3Windows(dest=C:\redacted\.package, clear=False, global=False) [INFO session:52]
272 write C:\redacted\.package\pyvenv.cfg [DEBUG pyenv_cfg:34]
273     home = C:\redacted [DEBUG pyenv_cfg:38]
274     implementation = CPython [DEBUG pyenv_cfg:38]
282     version_info = 3.7.9.final.0 [DEBUG pyenv_cfg:38]
285     virtualenv = 20.0.34 [DEBUG pyenv_cfg:38]
292     include-system-site-packages = false [DEBUG pyenv_cfg:38]
296     base-prefix = C:\redacted [DEBUG pyenv_cfg:38]
297     base-exec-prefix = C:\redacted [DEBUG pyenv_cfg:38]
305     base-executable = C:\redacted\python.exe [DEBUG pyenv_cfg:38]
311 copy C:\redacted\.package\Scripts\python.exe [DEBUG _sync:52]
Traceback (most recent call last):
  File "C:\redacted\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\redacted\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\redacted\lib\site-packages\virtualenv\__main__.py", line 77, in <module>
    run_with_catch()  # pragma: no cov
  File "C:\redacted\lib\site-packages\virtualenv\__main__.py", line 62, in run_with_catch
    run(args, options)
  File "C:\redacted\lib\site-packages\virtualenv\__main__.py", line 16, in run
    session = cli_run(args, options)
  File "C:\redacted\lib\site-packages\virtualenv\run\__init__.py", line 28, in cli_run
    of_session.run()
  File "C:\redacted\lib\site-packages\virtualenv\run\session.py", line 46, in run
    self._create()
  File "C:\redacted\lib\site-packages\virtualenv\run\session.py", line 53, in _create
    self.creator.run()
  File "C:\redacted\lib\site-packages\virtualenv\create\creator.py", line 161, in run
    self.create()
  File "C:\redacted\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 97, in create
    src.run(self, self.symlinks)
  File "C:\redacted\lib\site-packages\virtualenv\create\via_global_ref\builtin\ref.py", line 157, in run
    method(self.src, dest)
  File "C:\redacted\lib\site-packages\virtualenv\util\path\_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "C:\redacted\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\redacted\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\redacted\\Lib\\venv\\scripts\\nt\\python.exe'
```

Working run, with .33, same command
<details>

```console
262 setup logging to NOTSET [DEBUG report:43]
304 find interpreter for spec PythonSpec(path=C:\redacted\python.exe) [INFO builtin:44]
305 proposed PythonInfo(spec=CPython3.7.9.final.0-64, exe=C:\redacted\python.exe, platform=win32, version='3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
305 accepted PythonInfo(spec=CPython3.7.9.final.0-64, exe=C:\redacted\python.exe, platform=win32, version='3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:52]
311 symlink on filesystem does not work [DEBUG info:47]
311 filesystem is not case-sensitive [DEBUG info:28]
562 create virtual environment via CPython3Windows(dest=C:\redacted\.package, clear=False, global=False) [INFO session:52]
563 write C:\redacted\.package\pyvenv.cfg [DEBUG pyenv_cfg:34]
563     home = C:\redacted [DEBUG pyenv_cfg:38]
563     implementation = CPython [DEBUG pyenv_cfg:38]
563     version_info = 3.7.9.final.0 [DEBUG pyenv_cfg:38]
563     virtualenv = 20.0.33 [DEBUG pyenv_cfg:38]
563     include-system-site-packages = false [DEBUG pyenv_cfg:38]
564     base-prefix = C:\redacted [DEBUG pyenv_cfg:38]
564     base-exec-prefix = C:\redacted [DEBUG pyenv_cfg:38]
564     base-executable = C:\redacted\python.exe [DEBUG pyenv_cfg:38]
567 copy C:\redacted\.package\Scripts\python.exe [DEBUG _sync:52]
570 remove file C:\redacted\.package\Scripts\pythonw.exe [DEBUG _sync:38]
571 copy C:\redacted\.package\Scripts\pythonw.exe [DEBUG _sync:52]
578 remove file C:\redacted\.package\Scripts\api-ms-win-core-console-l1-1-0.dll [DEBUG _sync:38]
583 copy C:\redacted\.package\Scripts\api-ms-win-core-console-l1-1-0.dll [DEBUG _sync:52]
587 remove file C:\redacted\.package\Scripts\api-ms-win-core-datetime-l1-1-0.dll [DEBUG _sync:38]
595 copy C:\redacted\.package\Scripts\api-ms-win-core-datetime-l1-1-0.dll [DEBUG _sync:52]
601 remove file C:\redacted\.package\Scripts\api-ms-win-core-debug-l1-1-0.dll [DEBUG _sync:38]
606 copy C:\redacted\.package\Scripts\api-ms-win-core-debug-l1-1-0.dll [DEBUG _sync:52]
615 remove file C:\redacted\.package\Scripts\api-ms-win-core-errorhandling-l1-1-0.dll [DEBUG _sync:38]
618 copy C:\redacted\.package\Scripts\api-ms-win-core-errorhandling-l1-1-0.dll [DEBUG _sync:52]
624 remove file C:\redacted\.package\Scripts\api-ms-win-core-file-l1-1-0.dll [DEBUG _sync:38]
629 copy C:\redacted\.package\Scripts\api-ms-win-core-file-l1-1-0.dll [DEBUG _sync:52]
636 remove file C:\redacted\.package\Scripts\api-ms-win-core-file-l1-2-0.dll [DEBUG _sync:38]
640 copy C:\redacted\.package\Scripts\api-ms-win-core-file-l1-2-0.dll [DEBUG _sync:52]
660 remove file C:\redacted\.package\Scripts\api-ms-win-core-file-l2-1-0.dll [DEBUG _sync:38]
661 copy C:\redacted\.package\Scripts\api-ms-win-core-file-l2-1-0.dll [DEBUG _sync:52]
673 remove file C:\redacted\.package\Scripts\api-ms-win-core-handle-l1-1-0.dll [DEBUG _sync:38]
675 copy C:\redacted\.package\Scripts\api-ms-win-core-handle-l1-1-0.dll [DEBUG _sync:52]
692 remove file C:\redacted\.package\Scripts\api-ms-win-core-heap-l1-1-0.dll [DEBUG _sync:38]
696 copy C:\redacted\.package\Scripts\api-ms-win-core-heap-l1-1-0.dll [DEBUG _sync:52]
702 remove file C:\redacted\.package\Scripts\api-ms-win-core-interlocked-l1-1-0.dll [DEBUG _sync:38]
704 copy C:\redacted\.package\Scripts\api-ms-win-core-interlocked-l1-1-0.dll [DEBUG _sync:52]
710 remove file C:\redacted\.package\Scripts\api-ms-win-core-libraryloader-l1-1-0.dll [DEBUG _sync:38]
712 copy C:\redacted\.package\Scripts\api-ms-win-core-libraryloader-l1-1-0.dll [DEBUG _sync:52]
725 remove file C:\redacted\.package\Scripts\api-ms-win-core-localization-l1-2-0.dll [DEBUG _sync:38]
727 copy C:\redacted\.package\Scripts\api-ms-win-core-localization-l1-2-0.dll [DEBUG _sync:52]
740 remove file C:\redacted\.package\Scripts\api-ms-win-core-memory-l1-1-0.dll [DEBUG _sync:38]
741 copy C:\redacted\.package\Scripts\api-ms-win-core-memory-l1-1-0.dll [DEBUG _sync:52]
751 remove file C:\redacted\.package\Scripts\api-ms-win-core-namedpipe-l1-1-0.dll [DEBUG _sync:38]
752 copy C:\redacted\.package\Scripts\api-ms-win-core-namedpipe-l1-1-0.dll [DEBUG _sync:52]
764 remove file C:\redacted\.package\Scripts\api-ms-win-core-processenvironment-l1-1-0.dll [DEBUG _sync:38]
765 copy C:\redacted\.package\Scripts\api-ms-win-core-processenvironment-l1-1-0.dll [DEBUG _sync:52]
772 remove file C:\redacted\.package\Scripts\api-ms-win-core-processthreads-l1-1-0.dll [DEBUG _sync:38]
773 copy C:\redacted\.package\Scripts\api-ms-win-core-processthreads-l1-1-0.dll [DEBUG _sync:52]
783 remove file C:\redacted\.package\Scripts\api-ms-win-core-processthreads-l1-1-1.dll [DEBUG _sync:38]
784 copy C:\redacted\.package\Scripts\api-ms-win-core-processthreads-l1-1-1.dll [DEBUG _sync:52]
795 remove file C:\redacted\.package\Scripts\api-ms-win-core-profile-l1-1-0.dll [DEBUG _sync:38]
797 copy C:\redacted\.package\Scripts\api-ms-win-core-profile-l1-1-0.dll [DEBUG _sync:52]
809 remove file C:\redacted\.package\Scripts\api-ms-win-core-rtlsupport-l1-1-0.dll [DEBUG _sync:38]
810 copy C:\redacted\.package\Scripts\api-ms-win-core-rtlsupport-l1-1-0.dll [DEBUG _sync:52]
821 remove file C:\redacted\.package\Scripts\api-ms-win-core-string-l1-1-0.dll [DEBUG _sync:38]
826 copy C:\redacted\.package\Scripts\api-ms-win-core-string-l1-1-0.dll [DEBUG _sync:52]
837 remove file C:\redacted\.package\Scripts\api-ms-win-core-synch-l1-1-0.dll [DEBUG _sync:38]
838 copy C:\redacted\.package\Scripts\api-ms-win-core-synch-l1-1-0.dll [DEBUG _sync:52]
850 remove file C:\redacted\.package\Scripts\api-ms-win-core-synch-l1-2-0.dll [DEBUG _sync:38]
852 copy C:\redacted\.package\Scripts\api-ms-win-core-synch-l1-2-0.dll [DEBUG _sync:52]
860 remove file C:\redacted\.package\Scripts\api-ms-win-core-sysinfo-l1-1-0.dll [DEBUG _sync:38]
862 copy C:\redacted\.package\Scripts\api-ms-win-core-sysinfo-l1-1-0.dll [DEBUG _sync:52]
877 remove file C:\redacted\.package\Scripts\api-ms-win-core-timezone-l1-1-0.dll [DEBUG _sync:38]
881 copy C:\redacted\.package\Scripts\api-ms-win-core-timezone-l1-1-0.dll [DEBUG _sync:52]
890 remove file C:\redacted\.package\Scripts\api-ms-win-core-util-l1-1-0.dll [DEBUG _sync:38]
891 copy C:\redacted\.package\Scripts\api-ms-win-core-util-l1-1-0.dll [DEBUG _sync:52]
905 remove file C:\redacted\.package\Scripts\api-ms-win-crt-conio-l1-1-0.dll [DEBUG _sync:38]
907 copy C:\redacted\.package\Scripts\api-ms-win-crt-conio-l1-1-0.dll [DEBUG _sync:52]
910 remove file C:\redacted\.package\Scripts\api-ms-win-crt-convert-l1-1-0.dll [DEBUG _sync:38]
916 copy C:\redacted\.package\Scripts\api-ms-win-crt-convert-l1-1-0.dll [DEBUG _sync:52]
929 remove file C:\redacted\.package\Scripts\api-ms-win-crt-environment-l1-1-0.dll [DEBUG _sync:38]
930 copy C:\redacted\.package\Scripts\api-ms-win-crt-environment-l1-1-0.dll [DEBUG _sync:52]
934 remove file C:\redacted\.package\Scripts\api-ms-win-crt-filesystem-l1-1-0.dll [DEBUG _sync:38]
935 copy C:\redacted\.package\Scripts\api-ms-win-crt-filesystem-l1-1-0.dll [DEBUG _sync:52]
950 remove file C:\redacted\.package\Scripts\api-ms-win-crt-heap-l1-1-0.dll [DEBUG _sync:38]
951 copy C:\redacted\.package\Scripts\api-ms-win-crt-heap-l1-1-0.dll [DEBUG _sync:52]
957 remove file C:\redacted\.package\Scripts\api-ms-win-crt-locale-l1-1-0.dll [DEBUG _sync:38]
958 copy C:\redacted\.package\Scripts\api-ms-win-crt-locale-l1-1-0.dll [DEBUG _sync:52]
968 remove file C:\redacted\.package\Scripts\api-ms-win-crt-math-l1-1-0.dll [DEBUG _sync:38]
970 copy C:\redacted\.package\Scripts\api-ms-win-crt-math-l1-1-0.dll [DEBUG _sync:52]
983 remove file C:\redacted\.package\Scripts\api-ms-win-crt-multibyte-l1-1-0.dll [DEBUG _sync:38]
984 copy C:\redacted\.package\Scripts\api-ms-win-crt-multibyte-l1-1-0.dll [DEBUG _sync:52]
1000 remove file C:\redacted\.package\Scripts\api-ms-win-crt-private-l1-1-0.dll [DEBUG _sync:38]
1001 copy C:\redacted\.package\Scripts\api-ms-win-crt-private-l1-1-0.dll [DEBUG _sync:52]
1033 remove file C:\redacted\.package\Scripts\api-ms-win-crt-process-l1-1-0.dll [DEBUG _sync:38]
1035 copy C:\redacted\.package\Scripts\api-ms-win-crt-process-l1-1-0.dll [DEBUG _sync:52]
1043 remove file C:\redacted\.package\Scripts\api-ms-win-crt-runtime-l1-1-0.dll [DEBUG _sync:38]
1049 copy C:\redacted\.package\Scripts\api-ms-win-crt-runtime-l1-1-0.dll [DEBUG _sync:52]
1058 remove file C:\redacted\.package\Scripts\api-ms-win-crt-stdio-l1-1-0.dll [DEBUG _sync:38]
1063 copy C:\redacted\.package\Scripts\api-ms-win-crt-stdio-l1-1-0.dll [DEBUG _sync:52]
1075 remove file C:\redacted\.package\Scripts\api-ms-win-crt-string-l1-1-0.dll [DEBUG _sync:38]
1078 copy C:\redacted\.package\Scripts\api-ms-win-crt-string-l1-1-0.dll [DEBUG _sync:52]
1102 remove file C:\redacted\.package\Scripts\api-ms-win-crt-time-l1-1-0.dll [DEBUG _sync:38]
1103 copy C:\redacted\.package\Scripts\api-ms-win-crt-time-l1-1-0.dll [DEBUG _sync:52]
1115 remove file C:\redacted\.package\Scripts\api-ms-win-crt-utility-l1-1-0.dll [DEBUG _sync:38]
1120 copy C:\redacted\.package\Scripts\api-ms-win-crt-utility-l1-1-0.dll [DEBUG _sync:52]
1133 remove file C:\redacted\.package\Scripts\concrt140.dll [DEBUG _sync:38]
1136 copy C:\redacted\.package\Scripts\concrt140.dll [DEBUG _sync:52]
1149 remove file C:\redacted\.package\Scripts\msvcp140.dll [DEBUG _sync:38]
1151 copy C:\redacted\.package\Scripts\msvcp140.dll [DEBUG _sync:52]
1164 remove file C:\redacted\.package\Scripts\msvcp140_1.dll [DEBUG _sync:38]
1166 copy C:\redacted\.package\Scripts\msvcp140_1.dll [DEBUG _sync:52]
1189 remove file C:\redacted\.package\Scripts\msvcp140_2.dll [DEBUG _sync:38]
1191 copy C:\redacted\.package\Scripts\msvcp140_2.dll [DEBUG _sync:52]
1204 remove file C:\redacted\.package\Scripts\python3.dll [DEBUG _sync:38]
1213 copy C:\redacted\.package\Scripts\python3.dll [DEBUG _sync:52]
1220 remove file C:\redacted\.package\Scripts\python37.dll [DEBUG _sync:38]
1228 copy C:\redacted\.package\Scripts\python37.dll [DEBUG _sync:52]
1258 remove file C:\redacted\.package\Scripts\ucrtbase.dll [DEBUG _sync:38]
1260 copy C:\redacted\.package\Scripts\ucrtbase.dll [DEBUG _sync:52]
1275 remove file C:\redacted\.package\Scripts\vccorlib140.dll [DEBUG _sync:38]
1277 copy C:\redacted\.package\Scripts\vccorlib140.dll [DEBUG _sync:52]
1287 remove file C:\redacted\.package\Scripts\vcomp140.dll [DEBUG _sync:38]
1290 copy C:\redacted\.package\Scripts\vcomp140.dll [DEBUG _sync:52]
1307 remove file C:\redacted\.package\Scripts\vcruntime140.dll [DEBUG _sync:38]
1311 copy C:\redacted\.package\Scripts\vcruntime140.dll [DEBUG _sync:52]
1320 remove file C:\redacted\.package\Scripts\pyexpat.pyd [DEBUG _sync:38]
1322 copy C:\redacted\.package\Scripts\pyexpat.pyd [DEBUG _sync:52]
1337 remove file C:\redacted\.package\Scripts\select.pyd [DEBUG _sync:38]
1341 copy C:\redacted\.package\Scripts\select.pyd [DEBUG _sync:52]
1348 remove file C:\redacted\.package\Scripts\tcl86t.dll [DEBUG _sync:38]
1356 copy C:\redacted\.package\Scripts\tcl86t.dll [DEBUG _sync:52]
1431 remove file C:\redacted\.package\Scripts\tk86t.dll [DEBUG _sync:38]
1434 copy C:\redacted\.package\Scripts\tk86t.dll [DEBUG _sync:52]
3299 remove file C:\redacted\.package\Scripts\unicodedata.pyd [DEBUG _sync:38]
3301 copy C:\redacted\.package\Scripts\unicodedata.pyd [DEBUG _sync:52]
3352 remove file C:\redacted\.package\Scripts\winsound.pyd [DEBUG _sync:38]
3355 copy C:\redacted\.package\Scripts\winsound.pyd [DEBUG _sync:52]
3364 remove file C:\redacted\.package\Scripts\_asyncio.pyd [DEBUG _sync:38]
3366 copy C:\redacted\.package\Scripts\_asyncio.pyd [DEBUG _sync:52]
3379 remove file C:\redacted\.package\Scripts\_bz2.pyd [DEBUG _sync:38]
3381 copy C:\redacted\.package\Scripts\_bz2.pyd [DEBUG _sync:52]
3394 remove file C:\redacted\.package\Scripts\_ctypes.pyd [DEBUG _sync:38]
3400 copy C:\redacted\.package\Scripts\_ctypes.pyd [DEBUG _sync:52]
3407 remove file C:\redacted\.package\Scripts\_ctypes_test.pyd [DEBUG _sync:38]
3410 copy C:\redacted\.package\Scripts\_ctypes_test.pyd [DEBUG _sync:52]
3423 remove file C:\redacted\.package\Scripts\_decimal.pyd [DEBUG _sync:38]
3430 copy C:\redacted\.package\Scripts\_decimal.pyd [DEBUG _sync:52]
3441 remove file C:\redacted\.package\Scripts\_elementtree.pyd [DEBUG _sync:38]
3446 copy C:\redacted\.package\Scripts\_elementtree.pyd [DEBUG _sync:52]
3455 remove file C:\redacted\.package\Scripts\_hashlib.pyd [DEBUG _sync:38]
3458 copy C:\redacted\.package\Scripts\_hashlib.pyd [DEBUG _sync:52]
3472 remove file C:\redacted\.package\Scripts\_lzma.pyd [DEBUG _sync:38]
3474 copy C:\redacted\.package\Scripts\_lzma.pyd [DEBUG _sync:52]
3503 remove file C:\redacted\.package\Scripts\_msi.pyd [DEBUG _sync:38]
3504 copy C:\redacted\.package\Scripts\_msi.pyd [DEBUG _sync:52]
3512 remove file C:\redacted\.package\Scripts\_multiprocessing.pyd [DEBUG _sync:38]
3519 copy C:\redacted\.package\Scripts\_multiprocessing.pyd [DEBUG _sync:52]
3531 remove file C:\redacted\.package\Scripts\_overlapped.pyd [DEBUG _sync:38]
3538 copy C:\redacted\.package\Scripts\_overlapped.pyd [DEBUG _sync:52]
3549 remove file C:\redacted\.package\Scripts\_queue.pyd [DEBUG _sync:38]
3556 copy C:\redacted\.package\Scripts\_queue.pyd [DEBUG _sync:52]
3572 remove file C:\redacted\.package\Scripts\_socket.pyd [DEBUG _sync:38]
3576 copy C:\redacted\.package\Scripts\_socket.pyd [DEBUG _sync:52]
3588 remove file C:\redacted\.package\Scripts\_sqlite3.pyd [DEBUG _sync:38]
3591 copy C:\redacted\.package\Scripts\_sqlite3.pyd [DEBUG _sync:52]
3613 remove file C:\redacted\.package\Scripts\_ssl.pyd [DEBUG _sync:38]
3615 copy C:\redacted\.package\Scripts\_ssl.pyd [DEBUG _sync:52]
3626 remove file C:\redacted\.package\Scripts\_testbuffer.pyd [DEBUG _sync:38]
3629 copy C:\redacted\.package\Scripts\_testbuffer.pyd [DEBUG _sync:52]
3641 remove file C:\redacted\.package\Scripts\_testcapi.pyd [DEBUG _sync:38]
3644 copy C:\redacted\.package\Scripts\_testcapi.pyd [DEBUG _sync:52]
3660 remove file C:\redacted\.package\Scripts\_testconsole.pyd [DEBUG _sync:38]
3662 copy C:\redacted\.package\Scripts\_testconsole.pyd [DEBUG _sync:52]
3673 remove file C:\redacted\.package\Scripts\_testimportmultiple.pyd [DEBUG _sync:38]
3676 copy C:\redacted\.package\Scripts\_testimportmultiple.pyd [DEBUG _sync:52]
3689 remove file C:\redacted\.package\Scripts\_testmultiphase.pyd [DEBUG _sync:38]
3698 copy C:\redacted\.package\Scripts\_testmultiphase.pyd [DEBUG _sync:52]
3706 remove file C:\redacted\.package\Scripts\_tkinter.pyd [DEBUG _sync:38]
3708 copy C:\redacted\.package\Scripts\_tkinter.pyd [DEBUG _sync:52]
3747 create virtualenv import hook file C:\redacted\.package\Lib\site-packages\_virtualenv.pth [DEBUG api:95]
3750 create C:\redacted\.package\Lib\site-packages\_virtualenv.py [DEBUG api:98]
3754 ============================== target debug ============================== [DEBUG session:54]
3761 debug via 'C:\redacted\lib\site-packages\virtualenv\create\debug.py' [DEBUG creator:213]
3760 {
  "sys": {
    "executable": "C:\\redacted\\.package\\Scripts\\python.exe",
    "_base_executable": "C:\\redacted\\.package\\Scripts\\python.exe",
    "prefix": "C:\\redacted\\.package",
    "base_prefix": "C:\\redacted",
    "real_prefix": null,
    "exec_prefix": "C:\\redacted\\.package",
    "base_exec_prefix": "C:\\redacted",
    "path": [
      "C:\\redacted\\.package\\Scripts\\python37.zip",
      "C:\\redacted\\DLLs",
      "C:\\redacted\\lib",
      "C:\\redacted",
      "C:\\redacted\\.package",
      "C:\\redacted\\.package\\lib\\site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "cp1252"
  },
  "version": "3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]",
  "makefile_filename": "C:\\redacted\\Lib\\config\\Makefile",
  "os": "<module 'os' from 'C:\\\\redacted\\\\lib\\\\os.py'>",
  "site": "<module 'site' from 'C:\\\\redacted\\\\lib\\\\site.py'>",
  "datetime": "<module 'datetime' from 'C:\\\\redacted\\\\lib\\\\datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from 'C:\\\\redacted\\\\lib\\\\json\\\\__init__.py'>"
} [DEBUG session:55]
3968 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\redacted\AppData\Local\pypa\virtualenv) [INFO session:59]
3991 got embed update of distribution setuptools from C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\embed\1\setuptools.json [DEBUG via_disk_folder:133]
3992 got embed update of distribution pip from C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\embed\1\pip.json [DEBUG via_disk_folder:133]
3992 got embed update of distribution wheel from C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\embed\1\wheel.json [DEBUG via_disk_folder:133]
3997 got embed update of distribution setuptools from C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\embed\1\setuptools.json [DEBUG via_disk_folder:133]
4003 got embed update of distribution wheel from C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\embed\1\wheel.json [DEBUG via_disk_folder:133]
4003 got embed update of distribution pip from C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\embed\1\pip.json [DEBUG via_disk_folder:133]
4021 install setuptools from wheel C:\redacted\lib\site-packages\virtualenv\seed\wheels\embed\setuptools-50.3.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:51]
4024 install wheel from wheel C:\redacted\lib\site-packages\virtualenv\seed\wheels\embed\wheel-0.35.1-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:51]
4025 install pip from wheel C:\redacted\lib\site-packages\virtualenv\seed\wheels\embed\pip-20.2.3-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:51]
4025 Attempting to acquire lock 1965456835400 on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [DEBUG filelock:270]
4026 Attempting to acquire lock 1965456834696 on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [DEBUG filelock:270]
4034 Attempting to acquire lock 1965456835208 on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [DEBUG filelock:270]
4037 Lock 1965456835400 acquired on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [INFO filelock:274]
4046 Lock 1965456834696 acquired on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [INFO filelock:274]
4049 Lock 1965456835208 acquired on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [INFO filelock:274]
4056 Attempting to release lock 1965456835400 on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [DEBUG filelock:315]
4057 Attempting to release lock 1965456834696 on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [DEBUG filelock:315]
4059 Attempting to release lock 1965456835208 on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [DEBUG filelock:315]
4069 Lock 1965456835400 released on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\setuptools-50.3.0-py3-none-any.lock [INFO filelock:318]
4071 Lock 1965456834696 released on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\wheel-0.35.1-py2.py3-none-any.lock [INFO filelock:318]
4079 Lock 1965456835208 released on C:\redacted\AppData\Local\pypa\virtualenv\wheel\3.7\image\1\CopyPipInstall\pip-20.2.3-py2.py3-none-any.lock [INFO filelock:318]
4084 copy C:\redacted\.package\Lib\site-packages\distutils-precedence.pth [DEBUG _sync:52]
4111 copy C:\redacted\.package\Lib\site-packages\easy_install.py [DEBUG _sync:52]
4115 copy directory C:\redacted\.package\Lib\site-packages\wheel [DEBUG _sync:52]
4149 copy directory C:\redacted\.package\Lib\site-packages\pkg_resources [DEBUG _sync:52]
4311 copy directory C:\redacted\.package\Lib\site-packages\wheel-0.35.1.dist-info [DEBUG _sync:52]
4337 copy directory C:\redacted\.package\Lib\site-packages\pip [DEBUG _sync:52]
4386 copy C:\redacted\.package\Lib\site-packages\wheel-0.35.1.virtualenv [DEBUG _sync:52]
4393 copy directory C:\redacted\.package\Lib\site-packages\setuptools [DEBUG _sync:52]
4401 generated console scripts wheel.exe wheel3.7.exe wheel3.exe wheel-3.7.exe [DEBUG base:48]
5452 copy directory C:\redacted\.package\Lib\site-packages\setuptools-50.3.0.dist-info [DEBUG _sync:52]
5523 copy C:\redacted\.package\Lib\site-packages\setuptools-50.3.0.virtualenv [DEBUG _sync:52]
5528 copy directory C:\redacted\.package\Lib\site-packages\_distutils_hack [DEBUG _sync:52]
5561 generated console scripts easy_install3.7.exe easy_install.exe easy_install-3.7.exe easy_install3.exe [DEBUG base:48]
7421 copy directory C:\redacted\.package\Lib\site-packages\pip-20.2.3.dist-info [DEBUG _sync:52]
7467 copy C:\redacted\.package\Lib\site-packages\pip-20.2.3.virtualenv [DEBUG _sync:52]
7476 generated console scripts pip3.7.exe pip3.exe pip-3.7.exe pip.exe [DEBUG base:48]
7476 add activators for Bash, Batch, Fish, PowerShell, Python, Xonsh [INFO session:66]
7542 write C:\redacted\.package\pyvenv.cfg [DEBUG pyenv_cfg:34]
7542    home = C:\redacted [DEBUG pyenv_cfg:38]
7544    implementation = CPython [DEBUG pyenv_cfg:38]
7553    version_info = 3.7.9.final.0 [DEBUG pyenv_cfg:38]
7555    virtualenv = 20.0.33 [DEBUG pyenv_cfg:38]
7556    include-system-site-packages = false [DEBUG pyenv_cfg:38]
7566    base-prefix = C:\redacted [DEBUG pyenv_cfg:38]
7576    base-exec-prefix = C:\redacted [DEBUG pyenv_cfg:38]
7577    base-executable = C:\redacted\python.exe [DEBUG pyenv_cfg:38]
7580 created virtual environment CPython3.7.9.final.0-64 in 7320ms
  creator CPython3Windows(dest=C:\redacted\.package, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\redacted\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.2.3, setuptools==50.3.0, wheel==0.35.1
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:17]
```

</details>

**Comment by drewgilliam** [comment] 2020-10-20 13:29
See https://github.com/pypa/virtualenv/issues/1986 and https://github.com/ContinuumIO/anaconda-issues/issues/12094

**Comment by gaborbernat** [comment] 2020-10-21 06:38
Duplicate of #1986

**Closed** 2020-10-21 06:38 UTC
Labels: bug
