### ISSUE TITLE
Can't use in conda

### ISSUE THREAD

**Issue by whg517** [pypa/virtualenv#2012] opened 2020-11-18 07:05 UTC
**Issue**

An error occurred while I was creating the virtual environment under Conda

**Environment**

Provide at least:
- OS: Windows 10 (19041.388)
- ``pip list`` of the host python where ``virtualenv`` is installed:

  ```console
  C:\Users\test\AppData\Local\Temp\test>pip list
  Package                            Version
  ---------------------------------- -------------------
  alabaster                          0.7.12
  anaconda-client                    1.7.2
  anaconda-navigator                 1.9.12
  anaconda-project                   0.8.3
  appdirs                            1.4.4
  argh                               0.26.2
  asn1crypto                         1.3.0
  astroid                            2.4.2
  astropy                            4.0.1.post1
  atomicwrites                       1.4.0
  attrs                              19.3.0
  autopep8                           1.5.3
  Babel                              2.8.0
  backcall                           0.2.0
  backports.functools-lru-cache      1.6.1
  backports.shutil-get-terminal-size 1.0.0
  backports.tempfile                 1.0
  backports.weakref                  1.0.post1
  bcrypt                             3.1.7
  beautifulsoup4                     4.9.1
  bitarray                           1.4.0
  bkcharts                           0.2
  bleach                             3.1.5
  bokeh                              2.1.1
  boto                               2.49.0
  Bottleneck                         1.3.2
  brotlipy                           0.7.0
  certifi                            2020.6.20
  cffi                               1.14.0
  chardet                            3.0.4
  click                              7.1.2
  cloudpickle                        1.5.0
  clyent                             1.2.2
  colorama                           0.4.3
  comtypes                           1.1.7
  conda                              4.8.3
  conda-build                        3.18.11
  conda-package-handling             1.7.0
  conda-verify                       3.4.2
  contextlib2                        0.6.0.post1
  cryptography                       2.9.2
  cycler                             0.10.0
  Cython                             0.29.21
  cytoolz                            0.10.1
  dask                               2.20.0
  decorator                          4.4.2
  defusedxml                         0.6.0
  diff-match-patch                   20200713
  distlib                            0.3.1
  distributed                        2.20.0
  docutils                           0.16
  entrypoints                        0.3
  et-xmlfile                         1.0.1
  fastcache                          1.1.0
  filelock                           3.0.12
  flake8                             3.8.3
  Flask                              1.1.2
  fsspec                             0.7.4
  future                             0.18.2
  gevent                             20.6.2
  glob2                              0.7
  gmpy2                              2.0.8
  greenlet                           0.4.16
  h5py                               2.10.0
  HeapDict                           1.0.1
  html5lib                           1.1
  idna                               2.10
  imageio                            2.9.0
  imagesize                          1.2.0
  importlib-metadata                 1.7.0
  intervaltree                       3.0.2
  ipykernel                          5.3.2
  ipython                            7.16.1
  ipython-genutils                   0.2.0
  ipywidgets                         7.5.1
  isort                              4.3.21
  itsdangerous                       1.1.0
  jdcal                              1.4.1
  jedi                               0.17.1
  Jinja2                             2.11.2
  joblib                             0.16.0
  json5                              0.9.5
  jsonschema                         3.2.0
  jupyter                            1.0.0
  jupyter-client                     6.1.6
  jupyter-console                    6.1.0
  jupyter-core                       4.6.3
  jupyterlab                         2.1.5
  jupyterlab-server                  1.2.0
  keyring                            21.2.1
  kiwisolver                         1.2.0
  lazy-object-proxy                  1.4.3
  libarchive-c                       2.9
  llvmlite                           0.33.0+1.g022ab0f
  locket                             0.2.0
  lxml                               4.5.2
  MarkupSafe                         1.1.1
  matplotlib                         3.2.2
  mccabe                             0.6.1
  menuinst                           1.4.16
  mistune                            0.8.4
  mkl-fft                            1.1.0
  mkl-random                         1.1.1
  mkl-service                        2.3.0
  mock                               4.0.2
  more-itertools                     8.4.0
  mpmath                             1.1.0
  msgpack                            1.0.0
  multipledispatch                   0.6.0
  navigator-updater                  0.2.1
  nbconvert                          5.6.1
  nbformat                           5.0.7
  networkx                           2.4
  nltk                               3.5
  nose                               1.3.7
  notebook                           6.0.3
  numba                              0.50.1
  numexpr                            2.7.1
  numpy                              1.18.5
  numpydoc                           1.1.0
  olefile                            0.46
  openpyxl                           3.0.4
  packaging                          20.4
  pandas                             1.0.5
  pandocfilters                      1.4.2
  paramiko                           2.7.1
  parso                              0.7.0
  partd                              1.1.0
  path                               13.1.0
  pathlib2                           2.3.5
  pathtools                          0.1.2
  patsy                              0.5.1
  pep8                               1.7.1
  pexpect                            4.8.0
  pickleshare                        0.7.5
  Pillow                             7.2.0
  pip                                20.1.1
  pipenv                             2020.11.15
  pkginfo                            1.5.0.1
  pluggy                             0.13.1
  ply                                3.11
  prometheus-client                  0.8.0
  prompt-toolkit                     3.0.5
  psutil                             5.7.0
  py                                 1.9.0
  pycodestyle                        2.6.0
  pycosat                            0.6.3
  pycparser                          2.20
  pycurl                             7.43.0.5
  pydocstyle                         5.0.2
  pyflakes                           2.2.0
  Pygments                           2.6.1
  pylint                             2.5.3
  PyNaCl                             1.4.0
  pyodbc                             4.0.0-unsupported
  pyOpenSSL                          19.1.0
  pyparsing                          2.4.7
  pyreadline                         2.1
  pyrsistent                         0.16.0
  PySocks                            1.7.1
  pytest                             5.4.3
  python-dateutil                    2.8.1
  python-jsonrpc-server              0.3.4
  python-language-server             0.34.1
  pytz                               2020.1
  PyWavelets                         1.1.1
  pywin32                            227
  pywin32-ctypes                     0.2.0
  pywinpty                           0.5.7
  PyYAML                             5.3.1
  pyzmq                              19.0.1
  QDarkStyle                         2.8.1
  QtAwesome                          0.7.2
  qtconsole                          4.7.5
  QtPy                               1.9.0
  regex                              2020.6.8
  requests                           2.24.0
  rope                               0.17.0
  Rtree                              0.9.4
  ruamel-yaml                        0.15.87
  scikit-image                       0.16.2
  scikit-learn                       0.23.1
  scipy                              1.5.0
  seaborn                            0.10.1
  Send2Trash                         1.5.0
  setuptools                         49.2.0.post20200714
  simplegeneric                      0.8.1
  singledispatch                     3.4.0.3
  sip                                4.19.13
  six                                1.15.0
  snowballstemmer                    2.0.0
  sortedcollections                  1.2.1
  sortedcontainers                   2.2.2
  soupsieve                          2.0.1
  Sphinx                             3.1.2
  sphinxcontrib-applehelp            1.0.2
  sphinxcontrib-devhelp              1.0.2
  sphinxcontrib-htmlhelp             1.0.3
  sphinxcontrib-jsmath               1.0.1
  sphinxcontrib-qthelp               1.0.3
  sphinxcontrib-serializinghtml      1.1.4
  sphinxcontrib-websupport           1.2.3
  spyder                             4.1.4
  spyder-kernels                     1.9.2
  SQLAlchemy                         1.3.18
  statsmodels                        0.11.1
  sympy                              1.6.1
  tables                             3.6.1
  tblib                              1.6.0
  terminado                          0.8.3
  testpath                           0.4.4
  threadpoolctl                      2.1.0
  toml                               0.10.1
  toolz                              0.10.0
  tornado                            6.0.4
  tqdm                               4.47.0
  traitlets                          4.3.3
  typing-extensions                  3.7.4.2
  ujson                              1.35
  unicodecsv                         0.14.1
  urllib3                            1.25.9
  virtualenv                         20.1.0
  virtualenv-clone                   0.5.4
  watchdog                           0.10.3
  wcwidth                            0.2.5
  webencodings                       0.5.1
  Werkzeug                           1.0.1
  wheel                              0.34.2
  widgetsnbextension                 3.5.1
  win-inet-pton                      1.1.0
  win-unicode-console                0.5
  wincertstore                       0.2
  wrapt                              1.11.2
  xlrd                               1.2.0
  XlsxWriter                         1.2.9
  xlwings                            0.19.5
  xlwt                               1.3.0
  xmltodict                          0.12.0
  yapf                               0.30.0
  zict                               2.0.0
  zipp                               3.1.0
  zope.event                         4.4
  zope.interface                     4.7.1
  ```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
C:\Users\test\AppData\Local\Temp\test>virtualenv venv -vvv --with-traceback
194 setup logging to NOTSET [DEBUG report:43]
303 find interpreter for spec PythonSpec(path=c:\programdata\anaconda3\python.exe) [INFO builtin:51]
303 proposed PythonInfo(spec=CPython3.8.3.final.0-64, exe=c:\programdata\anaconda3\python.exe, platform=win32, version='3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:57]
305 accepted PythonInfo(spec=CPython3.8.3.final.0-64, exe=c:\programdata\anaconda3\python.exe, platform=win32, version='3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:59]
311 symlink on filesystem does not work [DEBUG info:47]
312 filesystem is not case-sensitive [DEBUG info:28]
401 create virtual environment via CPython3Windows(dest=C:\Users\test\AppData\Local\Temp\test\venv, clear=False, global=False) [INFO session:52]
402 create folder C:\Users\test\AppData\Local\Temp\test\venv\Lib\site-packages [DEBUG _sync:25]
402 create folder C:\Users\test\AppData\Local\Temp\test\venv\Scripts [DEBUG _sync:25]
404 write C:\Users\test\AppData\Local\Temp\test\venv\pyvenv.cfg [DEBUG pyenv_cfg:34]
404     home = c:\programdata\anaconda3 [DEBUG pyenv_cfg:38]
404     implementation = CPython [DEBUG pyenv_cfg:38]
404     version_info = 3.8.3.final.0 [DEBUG pyenv_cfg:38]
404     virtualenv = 20.1.0 [DEBUG pyenv_cfg:38]
404     include-system-site-packages = false [DEBUG pyenv_cfg:38]
405     base-prefix = c:\programdata\anaconda3 [DEBUG pyenv_cfg:38]
405     base-exec-prefix = c:\programdata\anaconda3 [DEBUG pyenv_cfg:38]
405     base-executable = c:\programdata\anaconda3\python.exe [DEBUG pyenv_cfg:38]
407 copy c:\programdata\anaconda3\Lib\venv\scripts\nt\python.exe to C:\Users\test\AppData\Local\Temp\test\venv\Scripts\python.exe [DEBUG _sync:52]
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\virtualenv.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\__main__.py", line 62, in run_with_catch
    run(args, options)
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\__main__.py", line 16, in run
    session = cli_run(args, options)
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\run\__init__.py", line 28, in cli_run
    of_session.run()
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\run\session.py", line 46, in run
    self._create()
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\run\session.py", line 53, in _create
    self.creator.run()
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\create\creator.py", line 161, in run
    self.create()
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 97, in create
    src.run(self, self.symlinks)
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\create\via_global_ref\builtin\ref.py", line 157, in run
    method(self.src, dest)
  File "c:\programdata\anaconda3\lib\site-packages\virtualenv\util\path\_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "c:\programdata\anaconda3\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\programdata\anaconda3\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\Lib\\venv\\scripts\\nt\\python.exe'

```

**Comment by gaborbernat** [comment] 2020-11-18 14:28
Duplicate of https://github.com/pypa/virtualenv/issues/1986

**Closed by gaborbernat** 2020-11-18 14:28 UTC
Labels: bug
