### ISSUE TITLE
link to virtualenv binary gets base sys.exec_prefix 

### ISSUE THREAD

**Issue by replabrobin** [pypa/virtualenv#1718] opened 2020-03-12 11:04 UTC
**Issue**

Using a link to the virtualenv python created using default options no longer finds the correct exec_prefix. This is also true even when --copies is used.

The problem is this after creation using --copies a link to the interpreter binary gets the wrong sys.exec prefix. This was not the case with legacy 16.7.2 (where by default the interpreter was copied).

```
rptlab@everest:~/code/hg-repos
$ ls -l __py__/382/bin/python bin/python382
lrwxrwxrwx 1 rptlab rptlab       24 Mar 12 10:46 bin/python382 -> ../__py__/382/bin/python
-rwxr-xr-x 1 rptlab rptlab 17386760 Mar 12 10:43 __py__/382/bin/python
rptlab@everest:~/code/hg-repos
$ bin/python382 -c"import sys;print('sys.exec_prefix',sys.exec_prefix,'\n\nsys.path','\n'.join(sys.path))"
sys.exec_prefix /home/rptlab/LOCAL/382 

sys.path 
/home/rptlab/LOCAL/382/lib/python38.zip
/home/rptlab/LOCAL/382/lib/python3.8
/home/rptlab/LOCAL/382/lib/python3.8/lib-dynload
/home/rptlab/LOCAL/382/lib/python3.8/site-packages
```

**Environment**

OS: ubuntu 18.04; python 3.8.2 

```
rptlab@everest:~/code/hg-repos
$ ~/LOCAL/382/bin/pip list
Package    Version
---------- -------
appdirs    1.4.3  
distlib    0.3.0  
filelock   3.0.12 
pip        20.0.2 
setuptools 45.2.0 
six        1.14.0 
virtualenv 20.0.8 
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```console
rptlab@everest:~/code/hg-repos
$ ~/LOCAL/382/bin/python3.8 -mvirtualenv -vvv --with-traceback --copies __py__/382 
31 setup logging to NOTSET [DEBUG report:43]
35 find interpreter for spec PythonSpec(path=/home/rptlab/LOCAL/382/bin/python3.8) [INFO builtin:44]
35 proposed PythonInfo(spec=CPython3.8.2.final.0-64, exe=/home/rptlab/LOCAL/382/bin/python3.8, platform=linux, version='3.8.2 (default, Mar  5 2020, 15:37:08) \n[GCC 7.4.0]', encoding_fs_io=utf-8-utf-8) [INFO builtin:50]
35 accepted PythonInfo(spec=CPython3.8.2.final.0-64, exe=/home/rptlab/LOCAL/382/bin/python3.8, platform=linux, version='3.8.2 (default, Mar  5 2020, 15:37:08) \n[GCC 7.4.0]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:52]
37 filesystem is case-sensitive [DEBUG info:28]
75 create virtual environment via CPython3Posix(dest=/home/rptlab/code/hg-repos/__py__/382, clear=False, global=False) [INFO session:52]
75 create folder /home/rptlab/code/hg-repos/__py__/382/bin [DEBUG _sync:21]
75 create folder /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages [DEBUG _sync:21]
75 write /home/rptlab/code/hg-repos/__py__/382/pyvenv.cfg [DEBUG pyenv_cfg:34]
75 	home = /home/rptlab/LOCAL/382 [DEBUG pyenv_cfg:38]
75 	implementation = CPython [DEBUG pyenv_cfg:38]
75 	version_info = 3.8.2.final.0 [DEBUG pyenv_cfg:38]
75 	virtualenv = 20.0.8 [DEBUG pyenv_cfg:38]
76 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
76 	base-prefix = /home/rptlab/LOCAL/382 [DEBUG pyenv_cfg:38]
76 	base-exec-prefix = /home/rptlab/LOCAL/382 [DEBUG pyenv_cfg:38]
76 	base-executable = /home/rptlab/LOCAL/382/bin/python3.8 [DEBUG pyenv_cfg:38]
76 copy /home/rptlab/LOCAL/382/bin/python3.8 to /home/rptlab/code/hg-repos/__py__/382/bin/python [DEBUG _sync:48]
84 copy /home/rptlab/LOCAL/382/bin/python3.8 to /home/rptlab/code/hg-repos/__py__/382/bin/python3 [DEBUG _sync:48]
92 copy /home/rptlab/LOCAL/382/bin/python3.8 to /home/rptlab/code/hg-repos/__py__/382/bin/python3.8 [DEBUG _sync:48]
101 create /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/_virtualenv.py [DEBUG api:60]
101 create virtualenv import hook file /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/_virtualenv.pth [DEBUG api:63]
101 ============================== target debug ============================== [DEBUG session:54]
101 debug via /home/rptlab/code/hg-repos/__py__/382/bin/python /home/rptlab/LOCAL/382/lib/python3.8/site-packages/virtualenv/create/debug.py [DEBUG creator:182]
101 {
  "sys": {
    "executable": "/home/rptlab/code/hg-repos/__py__/382/bin/python",
    "_base_executable": "/home/rptlab/code/hg-repos/__py__/382/bin/python",
    "prefix": "/home/rptlab/code/hg-repos/__py__/382",
    "base_prefix": "/home/rptlab/LOCAL/382",
    "real_prefix": null,
    "exec_prefix": "/home/rptlab/code/hg-repos/__py__/382",
    "base_exec_prefix": "/home/rptlab/LOCAL/382",
    "path": [
      "/home/rptlab/LOCAL/382/lib/python38.zip",
      "/home/rptlab/LOCAL/382/lib/python3.8",
      "/home/rptlab/LOCAL/382/lib/python3.8/lib-dynload",
      "/home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "utf-8"
  },
  "version": "3.8.2 (default, Mar  5 2020, 15:37:08) \n[GCC 7.4.0]",
  "os": "<module 'os' from '/home/rptlab/LOCAL/382/lib/python3.8/os.py'>",
  "site": "<module 'site' from '/home/rptlab/LOCAL/382/lib/python3.8/site.py'>",
  "datetime": "<module 'datetime' from '/home/rptlab/LOCAL/382/lib/python3.8/datetime.py'>",
  "math": "<module 'math' from '/home/rptlab/LOCAL/382/lib/python3.8/lib-dynload/math.cpython-38-x86_64-linux-gnu.so'>",
  "json": "<module 'json' from '/home/rptlab/LOCAL/382/lib/python3.8/json/__init__.py'>"
} [DEBUG session:55]
128 add seed packages via FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/rptlab/.local/share/virtualenv/seed-app-data/v1) [INFO session:59]
128 Attempting to acquire lock 140543598303504 on /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels.lock [DEBUG filelock:270]
128 Lock 140543598303504 acquired on /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels.lock [INFO filelock:274]
129 get bundled wheel /home/rptlab/LOCAL/382/lib/python3.8/site-packages/virtualenv/seed/embed/wheels/pip-20.0.2-py2.py3-none-any.whl [DEBUG acquire:51]
129 get bundled wheel /home/rptlab/LOCAL/382/lib/python3.8/site-packages/virtualenv/seed/embed/wheels/setuptools-45.2.0-py3-none-any.whl [DEBUG acquire:51]
130 get bundled wheel /home/rptlab/LOCAL/382/lib/python3.8/site-packages/virtualenv/seed/embed/wheels/wheel-0.34.2-py2.py3-none-any.whl [DEBUG acquire:51]
131 install wheel from wheel /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels/wheel-0.34.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:46]
131 install setuptools from wheel /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels/setuptools-45.2.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:46]
131 install pip from wheel /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels/pip-20.0.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:46]
132 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.dist-info to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/wheel-0.34.2.dist-info [DEBUG _sync:48]
132 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/setuptools-45.2.0.dist-info to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/setuptools-45.2.0.dist-info [DEBUG _sync:48]
132 copy /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip-20.0.2.virtualenv to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/pip-20.0.2.virtualenv [DEBUG _sync:48]
133 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/pip [DEBUG _sync:48]
135 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/wheel [DEBUG _sync:48]
136 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/setuptools to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/setuptools [DEBUG _sync:48]
139 copy /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.virtualenv to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/wheel-0.34.2.virtualenv [DEBUG _sync:48]
140 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/wheel to 775 [INFO util:566]
141 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/wheel-3.8 to 775 [INFO util:566]
141 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/wheel3 to 775 [INFO util:566]
141 generated console scripts wheel wheel3 wheel-3.8 [DEBUG base:53]
157 copy /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/setuptools-45.2.0.virtualenv to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/setuptools-45.2.0.virtualenv [DEBUG _sync:48]
158 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/pkg_resources to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/pkg_resources [DEBUG _sync:48]
162 copy /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/easy_install.py to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/easy_install.py [DEBUG _sync:48]
163 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/easy_install3 to 775 [INFO util:566]
164 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/easy_install-3.8 to 775 [INFO util:566]
164 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/easy_install to 775 [INFO util:566]
164 generated console scripts easy_install3 easy_install-3.8 easy_install [DEBUG base:53]
182 copy directory /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip-20.0.2.dist-info to /home/rptlab/code/hg-repos/__py__/382/lib/python3.8/site-packages/pip-20.0.2.dist-info [DEBUG _sync:48]
183 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/pip-3.8 to 775 [INFO util:566]
183 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/pip to 775 [INFO util:566]
183 changing mode of /home/rptlab/code/hg-repos/__py__/382/bin/pip3 to 775 [INFO util:566]
183 generated console scripts pip-3.8 pip3 pip [DEBUG base:53]
183 Attempting to release lock 140543598303504 on /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels.lock [DEBUG filelock:315]
183 Lock 140543598303504 released on /home/rptlab/.local/share/virtualenv/seed-app-data/v1/3.8/wheels.lock [INFO filelock:318]
183 add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [INFO session:64]
185 write /home/rptlab/code/hg-repos/__py__/382/pyvenv.cfg [DEBUG pyenv_cfg:34]
185 	home = /home/rptlab/LOCAL/382 [DEBUG pyenv_cfg:38]
185 	implementation = CPython [DEBUG pyenv_cfg:38]
185 	version_info = 3.8.2.final.0 [DEBUG pyenv_cfg:38]
185 	virtualenv = 20.0.8 [DEBUG pyenv_cfg:38]
185 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
185 	base-prefix = /home/rptlab/LOCAL/382 [DEBUG pyenv_cfg:38]
185 	base-exec-prefix = /home/rptlab/LOCAL/382 [DEBUG pyenv_cfg:38]
185 	base-executable = /home/rptlab/LOCAL/382/bin/python3.8 [DEBUG pyenv_cfg:38]
185 created virtual environment CPython3.8.2.final.0-64 in 155ms
  creator CPython3Posix(dest=/home/rptlab/code/hg-repos/__py__/382, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/rptlab/.local/share/virtualenv/seed-app-data/v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:21]

```

**Comment by gaborbernat** [comment] 2020-03-12 11:13
Duplicate of https://github.com/pypa/virtualenv/issues/1599#issuecomment-590306182

This kind of access to virtual environments is no longer supported by design for venvs https://github.com/pypa/virtualenv/issues/1599#issuecomment-590306182

**Closed by gaborbernat** 2020-03-12 11:13 UTC
Labels: bug

**Comment by replabrobin** [comment] 2020-03-12 11:25
So all the advantages of virtualenv seem to have disappeared. I'll continue to carry on using 16.7.x.

**Comment by gaborbernat** [comment] 2020-03-12 11:39
Well, not all, the opposite. See https://discuss.python.org/t/virtualenv-20-0-0-beta1-is-available/3077 for more details. This feature (that's rarely used) is the sacrifice of keeping the project alive.
