### ISSUE TITLE
virtualenv pip freeze returns system modules when space is in containing folder

### ISSUE THREAD

**Issue by fernando-mc** [pypa/virtualenv#1001] opened 2017-01-08 22:42 UTC
```
~/Desktop $ mkdir my\ test && cd my\ test
~/Desktop/my test $ virtualenv .env 
~/Desktop/my test $ source .env/bin/activate
(.env) ~/Desktop/my test $ pip freeze

```
This prints all system modules not just the ones in the virtual environment.

Happy to provide more context here as needed. I didn't see an issue template but I can add information as needed.

**Comment by HaraldNordgren** [comment] 2017-01-09 02:53
Duplicate of https://github.com/pypa/virtualenv/issues/994

**Closed** 2019-01-21 22:22 UTC
Labels: wontfix
