### ISSUE TITLE
Attempting to create a virtualenv from a python3.5 instance

### ISSUE THREAD

**Issue by rawrgulmuffins** [pypa/virtualenv#745] opened 2015-04-13 18:43 UTC
On osx verison 10.10.2 I ran

```
$ hg clone https://hg.python.org/cpython
$ cd cpython
$ ./configure --with-pydebug && make -j2
```

And then attempted to build a virtual environment using

```
$ virtualenv --python=./python.exe ~/python3.5_virtualenv
Running virtualenv with interpreter ./python.exe
Using base prefix '/usr/local'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2338, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 984, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1180, in install_python
    copy_required_modules(home_dir, symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1118, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1083, in change_prefix
    (filename, prefixes)
AssertionError: Filename /Users/alexlord/mercurial/cpython/Lib/os.py does not start with any of these         prefixes: ['/Users/alexlord/Library/Python/3.5/lib/python/site-packages',        '/Users/alexlord/.local/lib/python/3.5/site-packages', '/Users/alexlord/Library/Python/3.5/site-packages', '/Library/Python/3.5/site-packages', '/usr/local/Extras/lib/python', '/usr/local', '/usr/local']
```

I expected the virtualenv to built properly but I understand that pulling from mercurial might not be a supported use-case.

**Comment by rawrgulmuffins** [comment] 2015-04-13 19:54
Pulled 12.1.1 and reproed.

**Comment by Ivoz** [comment] 2015-10-02 10:36
Possibly sounds like the python you built needs it's `--prefix` configured correctly.

**Comment by jaraco** [comment] 2016-10-30 14:37
I believe this is a duplicate of #456.

**Closed** 2019-01-21 22:22 UTC
Labels: wontfix
