### ISSUE TITLE
Can't create new virtual environment under py2 after setuptools(45.0.0) which is never support py2

### ISSUE THREAD

**Issue by littlemo** [pypa/virtualenv#1496] opened 2020-01-13 08:32 UTC
Please add version limit for `setuptools` , like `setuptools~=44.0.0` , thanks
```
Collecting setuptools
  Created temporary directory: /private/var/folders/vg/4nf1fyxd26j3tjkt0yn5yxnm0000gn/T/pip-unpack-gj5u9h
  Resetting dropped connection: devpi.intra.xx.cn
  http://devpi.intra.xx.cn:80 "GET /root/mirror/%2Bf/616/b116b122e4140/setuptools-45.0.0-py2.py3-none-any.whl HTTP/1.1" 200 583778
  Downloading http://devpi.intra.xx.cn/root/mirror/%2Bf/616/b116b122e4140/setuptools-45.0.0-py2.py3-none-any.whl (583kB)
  Added setuptools from http://devpi.intra.xx.cn/root/mirror/%2Bf/616/b116b122e4140/setuptools-45.0.0-py2.py3-none-any.whl#md5=616b116b122e41402ae52f8706c4b372 to build tracker '/private/var/folders/vg/4nf1fyxd26j3tjkt0yn5yxnm0000gn/T/pip-req-tracker-ea12_L'
  Removed setuptools from http://devpi.intra.xx.cn/root/mirror/%2Bf/616/b116b122e4140/setuptools-45.0.0-py2.py3-none-any.whl#md5=616b116b122e41402ae52f8706c4b372 from build tracker '/private/var/folders/vg/4nf1fyxd26j3tjkt0yn5yxnm0000gn/T/pip-req-tracker-ea12_L'
Cleaning up...
Removed build tracker '/private/var/folders/vg/4nf1fyxd26j3tjkt0yn5yxnm0000gn/T/pip-req-tracker-ea12_L'
ERROR: Package 'setuptools' requires a different Python: 2.7.13 not in '>=3.5'
Exception information:
Traceback (most recent call last):
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/legacy_resolve.py", line 373, in _resolve_one
    ignore_requires_python=self.ignore_requires_python,
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv_support/pip-19.3.1-py2.py3-none-any.whl/pip/_internal/legacy_resolve.py", line 105, in _check_dist_requires_python
    dist.project_name, version, requires_python,
UnsupportedPythonVersion: Package 'setuptools' requires a different Python: 2.7.13 not in '>=3.5'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/moore/.pyenv/versions/2.7.13/bin/virtualenv", line 8, in <module>
    sys.exit(main())
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv.py", line 1179, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv.py", line 1023, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv.py", line 1116, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/Users/moore/.pyenv/versions/2.7.13/lib/python2.7/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /Volumes/Develop/test/test/bin/python2.7 - setuptools pip wheel failed with error code 1
```

**Comment by gaborbernat** [comment] 2020-01-13 08:56
We don't need too, the bundled pip automatically can understand python-requires of setuptools. I suspect this is a duplicate of https://github.com/pypa/virtualenv/issues/1493, if that's the case the bug is in your mirror, not in any of the software.

**Comment by nmajin** [comment] 2020-01-17 15:33
> We don't need too, the bundled pip automatically can understand python-requires of setuptools. I suspect this is a duplicate of #1493, if that's the case the bug is in your mirror, not in any of the software.

Can you expand? I have python 2.7.17 installed via homebrew on macOS. virtualenv is trying to install setuptools version 45 which is expecting python3

**Comment by pradyunsg** [comment] 2020-01-17 16:11
Which version of virtualenv is this?

Any recent version of pip wouldn't install setuptools 45 on Python 2 (there's a python_requires field for this), and virtualenv bundles a recent enough version of pip - one that understands the relevant metadata field.

**Comment by nmajin** [comment] 2020-01-17 18:28
> Which version of virtualenv is this?

I was on version 16.7.5, but then just recently updated to 16.7.9:

```
 ~  $  pip install --upgrade virtualenv
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: ...
Collecting virtualenv
  Downloading ...
Installing collected packages: virtualenv
  Found existing installation: virtualenv 16.7.5
    Uninstalling virtualenv-16.7.5:
      Successfully uninstalled virtualenv-16.7.5
Successfully installed virtualenv-16.7.9
```

Here is a test that fails:
```
 ~/Downloads  $  virtualenv venv-test
New python executable in /Users/<user>/Downloads/venv-test/bin/python2.7
Also creating executable in /Users/<user>/Downloads/venv-test/bin/python
Installing setuptools, pip, wheel...
...
Collecting setuptools
  Created temporary directory: /private/var/folders/v2/b8ls68sx1j5d0w44sz_1p1z5c9d2g4/T/pip-unpack-26EmuJ
  Looking up "...setuptools-45.0.0-py2.py3-none-any.whl" in the cache
  Current age based on date: 9989
...
ERROR: Package 'setuptools' requires a different Python: 2.7.17 not in '>=3.5'
```

Here is my environment:
```
 ~/Downloads  $  which pip
/usr/local/bin/pip
 ~/Downloads  $  pip -V
pip 19.3.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
 ~/Downloads  $  which python
/usr/local/bin/python
 ~/Downloads  $  python -V
Python 2.7.17

 ~/Downloads  $  pip show virtualenv
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Name: virtualenv
Version: 16.7.9
Summary: Virtual Python Environment builder
Home-page: https://virtualenv.pypa.io/
Author: Ian Bicking
Author-email: ianb@colorstudy.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: 
Required-by: 
```

**Comment by gaborbernat** [comment] 2020-01-17 20:43
can you replicate it with ``-no-download``?

**Comment by pfmoore** [comment] 2020-01-17 21:39
Also, do you have any sort of private PyPI mirror configured? If you have a mirror that doesn't supply the `data-requires-python` tag, pip won't know that setuptools 45.0.0 needs Python 3 when it looks for candidates, it will only find out once the install has been started - which would give the behaviour you are seeing.

> the bundled pip automatically can understand python-requires of setuptools

@gaborbernat How does virtualenv select which (bundled) setuptools to install? If it's relying on `Python-Requires` it has to use an index, not just a local directory with `--find-links`, for example...

**Comment by gaborbernat** [comment] 2020-01-17 21:41
Just delegates to pip, we just put what's available onto the find links.

**Comment by gaborbernat** [comment] 2020-01-17 21:42
We haven't updated the bundled package to 45.0 so that's why probably did not run into this yet 🤔

**Comment by gaborbernat** [comment] 2020-01-17 21:47
@pfmoore any way to install the correct wheel when the wheels are all in a folder? (No index) or is this unsupported?

**Comment by pfmoore** [comment] 2020-01-17 22:57
I don't believe so. The new pip resolver might handle `Requires-Python` in metadata the same as `data-requires-python` (i.e., skip the wheel rather than accepting it and then erroring) but that's not confirmed yet. (I *think* that I'd consider the current behaviour of installing and then raising an error as a bug, but I'd need to think about the implications a bit more before I'd state that definitively).

**Comment by gaborbernat** [comment] 2020-01-18 17:11
I'll create an issue in pip to discuss.

**Comment by pfmoore** [comment] 2020-01-18 17:39
You could of course manually special-case setuptools, and install `setuptools < 45.0.0` for Python 2. It's not a solution, but would be a reasonable workaround for now. (Sorry if that's a glaringly obvious idea 🙂)

**Comment by nmajin** [comment] 2020-01-21 01:27
> Also, do you have any sort of private PyPI mirror configured? If you have a mirror that doesn't supply the `data-requires-python` tag, pip won't know that setuptools 45.0.0 needs Python 3 when it looks for candidates, it will only find out once the install has been started - which would give the behaviour you are seeing.
> 
> > the bundled pip automatically can understand python-requires of setuptools
> 
> @gaborbernat How does virtualenv select which (bundled) setuptools to install? If it's relying on `Python-Requires` it has to use an index, not just a local directory with `--find-links`, for example...

Sorry for the late reply, so yes, I did confirm that the sonatype nexus repo is the issue. I haven't done research on this if sonatype was releasing a fix/feature or even has one for the `data-requires-python` tag, would you happen to know?

**Comment by fschulze** [comment] 2020-01-22 14:00
For anyone stumbling over this, for me the issue was an old devpi instance which didn't have support for ``data-requires-python``.

**Comment by asottile** [comment] 2020-01-29 01:53
at least for OP, this is probably that their mirror `http://devpi.intra.xx.cn:80` does not support the `data-requires-python` metadata

**Comment by gaborbernat** [comment] 2020-01-29 11:38
Closing for now as the underlying issue seems to be either in the mirrors or pip itself.

**Closed by gaborbernat** 2020-01-29 11:38 UTC
